// Comprehensive Ship Database (Tier 8 - 11)
// Generated from Wargaming API
// Date: 2025-12-16

let shipDatabase = [    { name: "Gustav den Store", speed: 31, type: "BB", nation: "Europe", tier: "9" },
    { name: "Karl XIV Johan", speed: 30.5, type: "BB", nation: "Europe", tier: "9" },
    { name: "Karl XIV Johan B", speed: 30.5, type: "BB", nation: "Europe", tier: "9" },
    { name: "Niord", speed: 32, type: "BB", nation: "Europe", tier: "9" },
    { name: "Alsace", speed: 30.4, type: "BB", nation: "France", tier: "9" },
    { name: "Jean Bart", speed: 30, type: "BB", nation: "France", tier: "9" },
    { name: "Jean Bart B", speed: 30, type: "BB", nation: "France", tier: "9" },
    { name: "Roussillon", speed: 32, type: "BB", nation: "France", tier: "9" },
    { name: "Friedrich der Grosse", speed: 27.3, type: "BB", nation: "Germany", tier: "9" },
    { name: "Pommern", speed: 31, type: "BB", nation: "Germany", tier: "9" },
    { name: "Pommern B", speed: 31, type: "BB", nation: "Germany", tier: "9" },
    { name: "Prinz Rupprecht", speed: 32, type: "BB", nation: "Germany", tier: "9" },
    { name: "Prinz Sigismund", speed: 33.5, type: "BB", nation: "Germany", tier: "9" },
    { name: "Giuseppe Verdi", speed: 32, type: "BB", nation: "Italy", tier: "9" },
    { name: "Lepanto", speed: 29.5, type: "BB", nation: "Italy", tier: "9" },
    { name: "Marco Polo", speed: 32, type: "BB", nation: "Italy", tier: "9" },
    { name: "Pilus Posterior", speed: 32, type: "BB", nation: "Italy", tier: "9" },
    { name: "Pilus Prior", speed: 32, type: "BB", nation: "Italy", tier: "9" },
    { name: "Adatara", speed: 30, type: "BB", nation: "Japan", tier: "9" },
    { name: "Daisen", speed: 35, type: "BB", nation: "Japan", tier: "9" },
    { name: "Hizen", speed: 28.2, type: "BB", nation: "Japan", tier: "9" },
    { name: "Hotaka", speed: 30, type: "BB", nation: "Japan", tier: "9" },
    { name: "Iwami", speed: 28.2, type: "BB", nation: "Japan", tier: "9" },
    { name: "Iwami B", speed: 28.2, type: "BB", nation: "Japan", tier: "9" },
    { name: "Izumo", speed: 27.2, type: "BB", nation: "Japan", tier: "9" },
    { name: "Musashi", speed: 27, type: "BB", nation: "Japan", tier: "9" },
    { name: "Tsurugi", speed: 35, type: "BB", nation: "Japan", tier: "9" },
    { name: "Los Andes", speed: 30, type: "BB", nation: "Pan-America", tier: "9" },
    { name: "Valparaíso", speed: 30, type: "BB", nation: "Pan-America", tier: "9" },
    { name: "Bajie", speed: 28, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Louchuan", speed: 29.5, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Sun Yat-Sen", speed: 28, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Taihang", speed: 28.2, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Wujing", speed: 32, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Xuan Ming", speed: 28, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Xuan Wu", speed: 33, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Yimeng", speed: 29, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Victoria", speed: 30, type: "BB", nation: "Spain", tier: "9" },
    { name: "Duncan", speed: 32, type: "BB", nation: "UK", tier: "9" },
    { name: "Lion", speed: 28, type: "BB", nation: "UK", tier: "9" },
    { name: "Marlborough", speed: 31.5, type: "BB", nation: "UK", tier: "9" },
    { name: "Scarlet Thunder", speed: 32, type: "BB", nation: "UK", tier: "9" },
    { name: "AL Kearsarge", speed: 30, type: "BB", nation: "USA", tier: "9" },
    { name: "Delaware", speed: 33, type: "BB", nation: "USA", tier: "9" },
    { name: "Georgia", speed: 33, type: "BB", nation: "USA", tier: "9" },
    { name: "Illinois", speed: 32.5, type: "BB", nation: "USA", tier: "9" },
    { name: "Indiana", speed: 27.5, type: "BB", nation: "USA", tier: "9" },
    { name: "Iowa", speed: 28.8, type: "BB", nation: "USA", tier: "9" },
    { name: "Iowa 2", speed: 33, type: "BB", nation: "USA", tier: "9" },
    { name: "Kearsarge", speed: 30, type: "BB", nation: "USA", tier: "9" },
    { name: "Kearsarge B", speed: 30, type: "BB", nation: "USA", tier: "9" },
    { name: "Minnesota", speed: 23, type: "BB", nation: "USA", tier: "9" },
    { name: "Missouri", speed: 33, type: "BB", nation: "USA", tier: "9" },
    { name: "AL Sov. Rossiya", speed: 28, type: "BB", nation: "USSR", tier: "9" },
    { name: "BA Hovercraft", speed: 29, type: "BB", nation: "USSR", tier: "9" },
    { name: "Navarin", speed: 27.5, type: "BB", nation: "USSR", tier: "9" },
    { name: "Sovetsky Soyuz", speed: 28, type: "BB", nation: "USSR", tier: "9" },
    { name: "Zarya Svobody", speed: 29, type: "BB", nation: "USSR", tier: "9" },
    { name: "Encounter", speed: 33, type: "CA", nation: "Commonwealth", tier: "9" },
    { name: "Hector", speed: 34, type: "CA", nation: "Commonwealth", tier: "9" },
    { name: "BA Utnapishtim's Ship", speed: 31.5, type: "CA", nation: "France", tier: "9" },
    { name: "Brest", speed: 31.5, type: "CA", nation: "France", tier: "9" },
    { name: "Carnot", speed: 34.5, type: "CA", nation: "France", tier: "9" },
    { name: "Le Havre", speed: 31.5, type: "CA", nation: "France", tier: "9" },
    { name: "Saint-Louis", speed: 33, type: "CA", nation: "France", tier: "9" },
    { name: "Admiral Schröder", speed: 32.5, type: "CA", nation: "Germany", tier: "9" },
    { name: "Ägir", speed: 33.5, type: "CA", nation: "Germany", tier: "9" },
    { name: "AL Ägir", speed: 33.5, type: "CA", nation: "Germany", tier: "9" },
    { name: "Blücher", speed: 32.8, type: "CA", nation: "Germany", tier: "9" },
    { name: "Manteuffel", speed: 32.5, type: "CA", nation: "Germany", tier: "9" },
    { name: "Roon", speed: 32.5, type: "CA", nation: "Germany", tier: "9" },
    { name: "Roon CLR", speed: 32.5, type: "CA", nation: "Germany", tier: "9" },
    { name: "Siegfried", speed: 33.5, type: "CA", nation: "Germany", tier: "9" },
    { name: "Brindisi", speed: 36.7, type: "CA", nation: "Italy", tier: "9" },
    { name: "Ferrante Gonzaga", speed: 35, type: "CA", nation: "Italy", tier: "9" },
    { name: "Messina", speed: 37, type: "CA", nation: "Italy", tier: "9" },
    { name: "Michelangelo", speed: 33, type: "CA", nation: "Italy", tier: "9" },
    { name: "AL Azuma", speed: 34, type: "CA", nation: "Japan", tier: "9" },
    { name: "Azuma", speed: 34, type: "CA", nation: "Japan", tier: "9" },
    { name: "Azuma B", speed: 34, type: "CA", nation: "Japan", tier: "9" },
    { name: "BA Takahashi", speed: 34.5, type: "CA", nation: "Japan", tier: "9" },
    { name: "Chikuma II", speed: 35.5, type: "CA", nation: "Japan", tier: "9" },
    { name: "Chikuma II Golden", speed: 35.5, type: "CA", nation: "Japan", tier: "9" },
    { name: "Ibuki", speed: 35, type: "CA", nation: "Japan", tier: "9" },
    { name: "Suzuya", speed: 35, type: "CA", nation: "Japan", tier: "9" },
    { name: "Suzuya Golden", speed: 35, type: "CA", nation: "Japan", tier: "9" },
    { name: "Suzuya VL", speed: 35, type: "CA", nation: "Japan", tier: "9" },
    { name: "Takahashi", speed: 34.5, type: "CA", nation: "Japan", tier: "9" },
    { name: "Johan de Witt", speed: 32.1, type: "CA", nation: "Netherlands", tier: "9" },
    { name: "Menno van Coehoorn", speed: 34, type: "CA", nation: "Netherlands", tier: "9" },
    { name: "Van Speijk", speed: 32.5, type: "CA", nation: "Netherlands", tier: "9" },
    { name: "Santander", speed: 33, type: "CA", nation: "Pan-America", tier: "9" },
    { name: "Dalian", speed: 33.4, type: "CA", nation: "Pan-Asia", tier: "9" },
    { name: "Mengchong", speed: 33.5, type: "CA", nation: "Pan-Asia", tier: "9" },
    { name: "Sejong", speed: 33, type: "CA", nation: "Pan-Asia", tier: "9" },
    { name: "Tianjin", speed: 33.5, type: "CA", nation: "Pan-Asia", tier: "9" },
    { name: "Almirante Oquendo", speed: 36, type: "CA", nation: "Spain", tier: "9" },
    { name: "Andalucía", speed: 36, type: "CA", nation: "Spain", tier: "9" },
    { name: "Drake", speed: 33.3, type: "CA", nation: "UK", tier: "9" },
    { name: "Neptune", speed: 33.5, type: "CA", nation: "UK", tier: "9" },
    { name: "Alaska", speed: 33, type: "CA", nation: "USA", tier: "9" },
    { name: "Alaska B", speed: 33, type: "CA", nation: "USA", tier: "9" },
    { name: "Buffalo", speed: 33, type: "CA", nation: "USA", tier: "9" },
    { name: "Cambridge", speed: 33, type: "CA", nation: "USA", tier: "9" },
    { name: "Seattle", speed: 33, type: "CA", nation: "USA", tier: "9" },
    { name: "Tulsa", speed: 33, type: "CA", nation: "USA", tier: "9" },
    { name: "Vallejo", speed: 32.5, type: "CA", nation: "USA", tier: "9" },
    { name: "Dmitri Donskoi", speed: 36, type: "CA", nation: "USSR", tier: "9" },
    { name: "Kozma Minin", speed: 36, type: "CA", nation: "USSR", tier: "9" },
    { name: "Kronshtadt", speed: 33.5, type: "CA", nation: "USSR", tier: "9" },
    { name: "Riga", speed: 33.5, type: "CA", nation: "USSR", tier: "9" },
    { name: "Vyazma", speed: 31.6, type: "CA", nation: "USSR", tier: "9" },
    { name: "Błyskawica '52", speed: 39, type: "DD", nation: "Europe", tier: "9" },
    { name: "Friesland", speed: 36, type: "DD", nation: "Europe", tier: "9" },
    { name: "Jäger", speed: 37, type: "DD", nation: "Europe", tier: "9" },
    { name: "Lambros Katsonis", speed: 38, type: "DD", nation: "Europe", tier: "9" },
    { name: "Östergötland", speed: 35, type: "DD", nation: "Europe", tier: "9" },
    { name: "Velos", speed: 38, type: "DD", nation: "Europe", tier: "9" },
    { name: "Mogador", speed: 43.5, type: "DD", nation: "France", tier: "9" },
    { name: "Orage", speed: 34, type: "DD", nation: "France", tier: "9" },
    { name: "Felix Schultz", speed: 37.5, type: "DD", nation: "Germany", tier: "9" },
    { name: "Z-44", speed: 36.5, type: "DD", nation: "Germany", tier: "9" },
    { name: "Z-46", speed: 37.5, type: "DD", nation: "Germany", tier: "9" },
    { name: "ZF-6", speed: 35, type: "DD", nation: "Germany", tier: "9" },
    { name: "ZF-6 Golden", speed: 35, type: "DD", nation: "Germany", tier: "9" },
    { name: "Adriatico", speed: 39, type: "DD", nation: "Italy", tier: "9" },
    { name: "Paolo Emilio", speed: 43.5, type: "DD", nation: "Italy", tier: "9" },
    { name: "Kitakaze", speed: 36, type: "DD", nation: "Japan", tier: "9" },
    { name: "Minegumo", speed: 35, type: "DD", nation: "Japan", tier: "9" },
    { name: "STAR Kitakaze", speed: 36, type: "DD", nation: "Japan", tier: "9" },
    { name: "Yūgumo", speed: 35.5, type: "DD", nation: "Japan", tier: "9" },
    { name: "Groningen", speed: 36, type: "DD", nation: "Netherlands", tier: "9" },
    { name: "Chung Mu", speed: 38, type: "DD", nation: "Pan-Asia", tier: "9" },
    { name: "Nanning", speed: 37, type: "DD", nation: "Pan-Asia", tier: "9" },
    { name: "Barfleur", speed: 34, type: "DD", nation: "UK", tier: "9" },
    { name: "Jutland", speed: 34, type: "DD", nation: "UK", tier: "9" },
    { name: "Somme", speed: 34, type: "DD", nation: "UK", tier: "9" },
    { name: "Benham", speed: 36.5, type: "DD", nation: "USA", tier: "9" },
    { name: "Black", speed: 35, type: "DD", nation: "USA", tier: "9" },
    { name: "Black B", speed: 35, type: "DD", nation: "USA", tier: "9" },
    { name: "Christopher", speed: 36, type: "DD", nation: "USA", tier: "9" },
    { name: "Fletcher", speed: 36.5, type: "DD", nation: "USA", tier: "9" },
    { name: "Frank Friday", speed: 38, type: "DD", nation: "USA", tier: "9" },
    { name: "GQ Johnny", speed: 38, type: "DD", nation: "USA", tier: "9" },
    { name: "Halford", speed: 38, type: "DD", nation: "USA", tier: "9" },
    { name: "Johnston", speed: 38, type: "DD", nation: "USA", tier: "9" },
    { name: "Neustrashimy", speed: 36, type: "DD", nation: "USSR", tier: "9" },
    { name: "Neustrashimy B", speed: 36, type: "DD", nation: "USSR", tier: "9" },
    { name: "Tashkent", speed: 42.5, type: "DD", nation: "USSR", tier: "9" },
    { name: "Udaloi", speed: 40, type: "DD", nation: "USSR", tier: "9" },
    { name: "Enigheten", speed: 30, type: "BB", nation: "Europe", tier: "8" },
    { name: "Turgut Reis", speed: 31.9, type: "BB", nation: "Europe", tier: "8" },
    { name: "Champagne", speed: 34, type: "BB", nation: "France", tier: "8" },
    { name: "Flandre", speed: 33.5, type: "BB", nation: "France", tier: "8" },
    { name: "Gascogne", speed: 32, type: "BB", nation: "France", tier: "8" },
    { name: "Picardie", speed: 27, type: "BB", nation: "France", tier: "8" },
    { name: "Richelieu", speed: 30.4, type: "BB", nation: "France", tier: "8" },
    { name: "AL Bismarck", speed: 31, type: "BB", nation: "Germany", tier: "8" },
    { name: "Anhalt", speed: 25, type: "BB", nation: "Germany", tier: "8" },
    { name: "BA Tirpitz", speed: 30.5, type: "BB", nation: "Germany", tier: "8" },
    { name: "Bismarck", speed: 28.5, type: "BB", nation: "Germany", tier: "8" },
    { name: "Brandenburg", speed: 32.5, type: "BB", nation: "Germany", tier: "8" },
    { name: "Brandenburg B", speed: 32.5, type: "BB", nation: "Germany", tier: "8" },
    { name: "Odin", speed: 30, type: "BB", nation: "Germany", tier: "8" },
    { name: "Odin TE", speed: 30, type: "BB", nation: "Germany", tier: "8" },
    { name: "Tirpitz", speed: 30.5, type: "BB", nation: "Germany", tier: "8" },
    { name: "Tirpitz B", speed: 30.5, type: "BB", nation: "Germany", tier: "8" },
    { name: "Wahnsinn", speed: 31, type: "BB", nation: "Germany", tier: "8" },
    { name: "Zieten", speed: 31, type: "BB", nation: "Germany", tier: "8" },
    { name: "AL Littorio", speed: 30, type: "BB", nation: "Italy", tier: "8" },
    { name: "BA Binah", speed: 29, type: "BB", nation: "Italy", tier: "8" },
    { name: "Marcantonio Colonna", speed: 29, type: "BB", nation: "Italy", tier: "8" },
    { name: "Roma", speed: 30, type: "BB", nation: "Italy", tier: "8" },
    { name: "Roma Aeterna", speed: 30, type: "BB", nation: "Italy", tier: "8" },
    { name: "Vittorio Veneto", speed: 30, type: "BB", nation: "Italy", tier: "8" },
    { name: "Amagi", speed: 28.1, type: "BB", nation: "Japan", tier: "8" },
    { name: "Ignis Purgatio", speed: 30, type: "BB", nation: "Japan", tier: "8" },
    { name: "Kii", speed: 29.5, type: "BB", nation: "Japan", tier: "8" },
    { name: "Ragnarok", speed: 30, type: "BB", nation: "Japan", tier: "8" },
    { name: "Yumihari", speed: 30, type: "BB", nation: "Japan", tier: "8" },
    { name: "Atlântico", speed: 25, type: "BB", nation: "Pan-America", tier: "8" },
    { name: "Ipiranga", speed: 29, type: "BB", nation: "Pan-America", tier: "8" },
    { name: "Hawke", speed: 30.5, type: "BB", nation: "UK", tier: "8" },
    { name: "Monarch", speed: 26.6, type: "BB", nation: "UK", tier: "8" },
    { name: "Vanguard", speed: 30, type: "BB", nation: "UK", tier: "8" },
    { name: "Alabama", speed: 27.5, type: "BB", nation: "USA", tier: "8" },
    { name: "Alabama B", speed: 27.5, type: "BB", nation: "USA", tier: "8" },
    { name: "Alabama ST", speed: 27.5, type: "BB", nation: "USA", tier: "8" },
    { name: "Alabama VL", speed: 27.5, type: "BB", nation: "USA", tier: "8" },
    { name: "Constellation", speed: 33.3, type: "BB", nation: "USA", tier: "8" },
    { name: "Kansas", speed: 23, type: "BB", nation: "USA", tier: "8" },
    { name: "Massachusetts", speed: 27.5, type: "BB", nation: "USA", tier: "8" },
    { name: "Massachusetts B", speed: 27.5, type: "BB", nation: "USA", tier: "8" },
    { name: "Nebraska", speed: 30, type: "BB", nation: "USA", tier: "8" },
    { name: "North Carolina", speed: 24.4, type: "BB", nation: "USA", tier: "8" },
    { name: "North Carolina 2", speed: 27.5, type: "BB", nation: "USA", tier: "8" },
    { name: "North Carolina CLR", speed: 27.5, type: "BB", nation: "USA", tier: "8" },
    { name: "Tennessee", speed: 20.5, type: "BB", nation: "USA", tier: "8" },
    { name: "Volunteer State", speed: 20.5, type: "BB", nation: "USA", tier: "8" },
    { name: "Borodino", speed: 31.6, type: "BB", nation: "USSR", tier: "8" },
    { name: "Borodino TE", speed: 31.6, type: "BB", nation: "USSR", tier: "8" },
    { name: "Lenin", speed: 28.5, type: "BB", nation: "USSR", tier: "8" },
    { name: "Vladivostok", speed: 29, type: "BB", nation: "USSR", tier: "8" },
    { name: "Auckland", speed: 33, type: "CA", nation: "Commonwealth", tier: "8" },
    { name: "Bayard", speed: 34, type: "CA", nation: "France", tier: "8" },
    { name: "Charles Martel", speed: 32.5, type: "CA", nation: "France", tier: "8" },
    { name: "Cherbourg", speed: 31.9, type: "CA", nation: "France", tier: "8" },
    { name: "Metz", speed: 30, type: "CA", nation: "France", tier: "8" },
    { name: "Admiral Hipper", speed: 32, type: "CA", nation: "Germany", tier: "8" },
    { name: "Cross of Dorn", speed: 32, type: "CA", nation: "Germany", tier: "8" },
    { name: "Knesebeck", speed: 32.5, type: "CA", nation: "Germany", tier: "8" },
    { name: "Mainz", speed: 32, type: "CA", nation: "Germany", tier: "8" },
    { name: "Mainz B", speed: 32, type: "CA", nation: "Germany", tier: "8" },
    { name: "Prinz Eugen", speed: 32, type: "CA", nation: "Germany", tier: "8" },
    { name: "Schill", speed: 32.5, type: "CA", nation: "Germany", tier: "8" },
    { name: "Schill B", speed: 32.5, type: "CA", nation: "Germany", tier: "8" },
    { name: "Wiesbaden", speed: 32, type: "CA", nation: "Germany", tier: "8" },
    { name: "Amalfi", speed: 37, type: "CA", nation: "Italy", tier: "8" },
    { name: "ARP Maya", speed: 35.5, type: "CA", nation: "Japan", tier: "8" },
    { name: "ARP Takao", speed: 35.5, type: "CA", nation: "Japan", tier: "8" },
    { name: "Atago", speed: 35.5, type: "CA", nation: "Japan", tier: "8" },
    { name: "Atago B", speed: 35.5, type: "CA", nation: "Japan", tier: "8" },
    { name: "Mogami", speed: 34.5, type: "CA", nation: "Japan", tier: "8" },
    { name: "Shimanto", speed: 34.5, type: "CA", nation: "Japan", tier: "8" },
    { name: "Tone", speed: 35.5, type: "CA", nation: "Japan", tier: "8" },
    { name: "Admiraal", speed: 32, type: "CA", nation: "Netherlands", tier: "8" },
    { name: "De Zeven Provinciën", speed: 32, type: "CA", nation: "Netherlands", tier: "8" },
    { name: "Haarlem", speed: 32.5, type: "CA", nation: "Netherlands", tier: "8" },
    { name: "Jaarsveld", speed: 34, type: "CA", nation: "Netherlands", tier: "8" },
    { name: "Statenland", speed: 32, type: "CA", nation: "Netherlands", tier: "8" },
    { name: "Vrijheid", speed: 33, type: "CA", nation: "Netherlands", tier: "8" },
    { name: "Almirante Grau", speed: 32, type: "CA", nation: "Pan-America", tier: "8" },
    { name: "Comandante Aguirre", speed: 32.5, type: "CA", nation: "Pan-America", tier: "8" },
    { name: "Ignacio Allende", speed: 33, type: "CA", nation: "Pan-America", tier: "8" },
    { name: "Harbin", speed: 33.4, type: "CA", nation: "Pan-Asia", tier: "8" },
    { name: "Irian", speed: 32.7, type: "CA", nation: "Pan-Asia", tier: "8" },
    { name: "Narai", speed: 30.3, type: "CA", nation: "Pan-Asia", tier: "8" },
    { name: "Piñatian", speed: 32.7, type: "CA", nation: "Pan-Asia", tier: "8" },
    { name: "Wukong", speed: 32.5, type: "CA", nation: "Pan-Asia", tier: "8" },
    { name: "Cataluña", speed: 37, type: "CA", nation: "Spain", tier: "8" },
    { name: "Numancia", speed: 33.5, type: "CA", nation: "Spain", tier: "8" },
    { name: "AL Cheshire", speed: 34, type: "CA", nation: "UK", tier: "8" },
    { name: "Albemarle", speed: 33, type: "CA", nation: "UK", tier: "8" },
    { name: "Belfast '43", speed: 32.5, type: "CA", nation: "UK", tier: "8" },
    { name: "Cheshire", speed: 34, type: "CA", nation: "UK", tier: "8" },
    { name: "Edinburgh", speed: 32.5, type: "CA", nation: "UK", tier: "8" },
    { name: "Érne", speed: 30.3, type: "CA", nation: "UK", tier: "8" },
    { name: "Hampshire", speed: 30, type: "CA", nation: "UK", tier: "8" },
    { name: "Nottingham", speed: 34, type: "CA", nation: "UK", tier: "8" },
    { name: "Sinann", speed: 32.5, type: "CA", nation: "UK", tier: "8" },
    { name: "STAR Edinburgh", speed: 32.5, type: "CA", nation: "UK", tier: "8" },
    { name: "Tiger '59", speed: 30.3, type: "CA", nation: "UK", tier: "8" },
    { name: "AL Montpelier", speed: 32.5, type: "CA", nation: "USA", tier: "8" },
    { name: "Anchorage", speed: 33, type: "CA", nation: "USA", tier: "8" },
    { name: "Baltimore", speed: 32.5, type: "CA", nation: "USA", tier: "8" },
    { name: "Bridgeport", speed: 33, type: "CA", nation: "USA", tier: "8" },
    { name: "Cleveland", speed: 32.5, type: "CA", nation: "USA", tier: "8" },
    { name: "Congress", speed: 33, type: "CA", nation: "USA", tier: "8" },
    { name: "Protector", speed: 33, type: "CA", nation: "USA", tier: "8" },
    { name: "Rochester", speed: 33, type: "CA", nation: "USA", tier: "8" },
    { name: "San Diego", speed: 32.5, type: "CA", nation: "USA", tier: "8" },
    { name: "Wichita", speed: 33.6, type: "CA", nation: "USA", tier: "8" },
    { name: "Bagration", speed: 34.5, type: "CA", nation: "USSR", tier: "8" },
    { name: "Chapayev", speed: 33.5, type: "CA", nation: "USSR", tier: "8" },
    { name: "Dmitry Pozharsky", speed: 33, type: "CA", nation: "USSR", tier: "8" },
    { name: "Kiberpankov", speed: 33, type: "CA", nation: "USSR", tier: "8" },
    { name: "Mikhail Kutuzov", speed: 33, type: "CA", nation: "USSR", tier: "8" },
    { name: "Ochakov", speed: 35, type: "CA", nation: "USSR", tier: "8" },
    { name: "Pyotr Bagration", speed: 34.5, type: "CA", nation: "USSR", tier: "8" },
    { name: "Tallinn", speed: 33.1, type: "CA", nation: "USSR", tier: "8" },
    { name: "August von Parseval", speed: 31.8, type: "CV", nation: "Germany", tier: "8" },
    { name: "Graf Zeppelin", speed: 32, type: "CV", nation: "Germany", tier: "8" },
    { name: "Graf Zeppelin B", speed: 32, type: "CV", nation: "Germany", tier: "8" },
    { name: "Aquila", speed: 30, type: "CV", nation: "Italy", tier: "8" },
    { name: "Kaga", speed: 28, type: "CV", nation: "Japan", tier: "8" },
    { name: "Kaga B", speed: 28, type: "CV", nation: "Japan", tier: "8" },
    { name: "Shōkaku", speed: 34, type: "CV", nation: "Japan", tier: "8" },
    { name: "Sanzang", speed: 33, type: "CV", nation: "Pan-Asia", tier: "8" },
    { name: "Colossus", speed: 25, type: "CV", nation: "UK", tier: "8" },
    { name: "Implacable", speed: 32, type: "CV", nation: "UK", tier: "8" },
    { name: "Indomitable", speed: 30.5, type: "CV", nation: "UK", tier: "8" },
    { name: "Theseus", speed: 25, type: "CV", nation: "UK", tier: "8" },
    { name: "AL Hornet", speed: 32.5, type: "CV", nation: "USA", tier: "8" },
    { name: "Enterprise", speed: 32.5, type: "CV", nation: "USA", tier: "8" },
    { name: "Hornet", speed: 32.5, type: "CV", nation: "USA", tier: "8" },
    { name: "Lexington", speed: 33, type: "CV", nation: "USA", tier: "8" },
    { name: "Saipan", speed: 33, type: "CV", nation: "USA", tier: "8" },
    { name: "Saipan B", speed: 33, type: "CV", nation: "USA", tier: "8" },
    { name: "Yorktown", speed: 32.5, type: "CV", nation: "USA", tier: "8" },
    { name: "Chkalov", speed: 32.3, type: "CV", nation: "USSR", tier: "8" },
    { name: "Chkalov B", speed: 32.3, type: "CV", nation: "USSR", tier: "8" },
    { name: "Pobeda", speed: 33.5, type: "CV", nation: "USSR", tier: "8" },
    { name: "Błyskawica '44", speed: 39, type: "DD", nation: "Europe", tier: "8" },
    { name: "Orkan", speed: 35, type: "DD", nation: "Europe", tier: "8" },
    { name: "Öland", speed: 35, type: "DD", nation: "Europe", tier: "8" },
    { name: "Split", speed: 38, type: "DD", nation: "Europe", tier: "8" },
    { name: "Hoche", speed: 36, type: "DD", nation: "France", tier: "8" },
    { name: "L'Aventurier", speed: 35, type: "DD", nation: "France", tier: "8" },
    { name: "Le Fantasque", speed: 42.7, type: "DD", nation: "France", tier: "8" },
    { name: "Le Terrible", speed: 43, type: "DD", nation: "France", tier: "8" },
    { name: "Gustav-Julius Maerker", speed: 36, type: "DD", nation: "Germany", tier: "8" },
    { name: "Z-23", speed: 37, type: "DD", nation: "Germany", tier: "8" },
    { name: "Z-35", speed: 36.5, type: "DD", nation: "Germany", tier: "8" },
    { name: "Vittorio Cuniberti", speed: 39, type: "DD", nation: "Italy", tier: "8" },
    { name: "Akizuki", speed: 33, type: "DD", nation: "Japan", tier: "8" },
    { name: "AL Yukikaze", speed: 35, type: "DD", nation: "Japan", tier: "8" },
    { name: "Asashio", speed: 35, type: "DD", nation: "Japan", tier: "8" },
    { name: "Asashio B", speed: 35, type: "DD", nation: "Japan", tier: "8" },
    { name: "HSF Harekaze", speed: 35.5, type: "DD", nation: "Japan", tier: "8" },
    { name: "HSF Harekaze II", speed: 35, type: "DD", nation: "Japan", tier: "8" },
    { name: "Kagerō", speed: 35, type: "DD", nation: "Japan", tier: "8" },
    { name: "Fenyang", speed: 33, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Hsienyang", speed: 37.5, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Loyang", speed: 38, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Loyang B", speed: 38, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Ship Smasha", speed: 33, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Siliwangi", speed: 36.5, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Zhu Que", speed: 38, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Cossack", speed: 36, type: "DD", nation: "UK", tier: "8" },
    { name: "Cossack B", speed: 36, type: "DD", nation: "UK", tier: "8" },
    { name: "Eskimo", speed: 36, type: "DD", nation: "UK", tier: "8" },
    { name: "Lightning", speed: 36, type: "DD", nation: "UK", tier: "8" },
    { name: "Benson", speed: 38, type: "DD", nation: "USA", tier: "8" },
    { name: "Kidd", speed: 38, type: "DD", nation: "USA", tier: "8" },
    { name: "Osborne", speed: 35, type: "DD", nation: "USA", tier: "8" },
    { name: "Kiev", speed: 42.5, type: "DD", nation: "USSR", tier: "8" },
    { name: "Ognevoi", speed: 37, type: "DD", nation: "USSR", tier: "8" },
    { name: "Provorny", speed: 36, type: "DD", nation: "USSR", tier: "8" },
    { name: "U-190", speed: 29, type: "SUB", nation: "Germany", tier: "8" },
    { name: "I-56", speed: 29, type: "SUB", nation: "Japan", tier: "8" },
    { name: "Alliance", speed: 31, type: "SUB", nation: "UK", tier: "8" },
    { name: "Sturdy", speed: 25, type: "SUB", nation: "UK", tier: "8" },
    { name: "Salmon", speed: 33, type: "SUB", nation: "USA", tier: "8" },
    { name: "L-20", speed: 29, type: "SUB", nation: "USSR", tier: "8" },
    { name: "S-189", speed: 30, type: "SUB", nation: "USSR", tier: "8" },
    { name: "Patrie", speed: 31, type: "BB", nation: "France", tier: "11" },
    { name: "Hannover", speed: 30, type: "BB", nation: "Germany", tier: "11" },
    { name: "Affondatore", speed: 30, type: "BB", nation: "Italy", tier: "11" },
    { name: "Satsuma", speed: 27, type: "BB", nation: "Japan", tier: "11" },
    { name: "Devastation", speed: 30.5, type: "BB", nation: "UK", tier: "11" },
    { name: "Maine", speed: 30.4, type: "BB", nation: "USA", tier: "11" },
    { name: "Admiral Ushakov", speed: 30, type: "BB", nation: "USSR", tier: "11" },
    { name: "Condé", speed: 34.5, type: "CA", nation: "France", tier: "11" },
    { name: "Clausewitz", speed: 32.5, type: "CA", nation: "Germany", tier: "11" },
    { name: "Piemonte", speed: 37, type: "CA", nation: "Italy", tier: "11" },
    { name: "Edgar", speed: 34, type: "CA", nation: "UK", tier: "11" },
    { name: "Annapolis", speed: 33, type: "CA", nation: "USA", tier: "11" },
    { name: "Jacksonville", speed: 34, type: "CA", nation: "USA", tier: "11" },
    { name: "Novosibirsk", speed: 34.5, type: "CA", nation: "USSR", tier: "11" },
    { name: "Sekiryu", speed: 35, type: "CV", nation: "Japan", tier: "11" },
    { name: "Eagle", speed: 31, type: "CV", nation: "UK", tier: "11" },
    { name: "United States", speed: 33, type: "CV", nation: "USA", tier: "11" },
    { name: "Dalarna", speed: 36, type: "DD", nation: "Europe", tier: "11" },
    { name: "Z-57", speed: 39, type: "DD", nation: "Germany", tier: "11" },
    { name: "Yamagiri", speed: 39.5, type: "DD", nation: "Japan", tier: "11" },
    { name: "Kunming", speed: 38, type: "DD", nation: "Pan-Asia", tier: "11" },
    { name: "Joshua Humphreys", speed: 37.2, type: "DD", nation: "USA", tier: "11" },
    { name: "Zorkiy", speed: 43, type: "DD", nation: "USSR", tier: "11" },
    { name: "Irresistible", speed: 31.5, type: "BB", nation: "Commonwealth", tier: "10" },
    { name: "Thor", speed: 33, type: "BB", nation: "Europe", tier: "10" },
    { name: "Bourgogne", speed: 32, type: "BB", nation: "France", tier: "10" },
    { name: "République", speed: 30, type: "BB", nation: "France", tier: "10" },
    { name: "[Grosser Kurfürst]", speed: 30, type: "BB", nation: "Germany", tier: "10" },
    { name: "Grosser Kurfürst", speed: 30, type: "BB", nation: "Germany", tier: "10" },
    { name: "Mecklenburg", speed: 32.5, type: "BB", nation: "Germany", tier: "10" },
    { name: "Preussen", speed: 30, type: "BB", nation: "Germany", tier: "10" },
    { name: "Schlieffen", speed: 34.1, type: "BB", nation: "Germany", tier: "10" },
    { name: "Schlieffen", speed: 34.1, type: "BB", nation: "Germany", tier: "10" },
    { name: "Von Zuckerhoff", speed: 34.1, type: "BB", nation: "Germany", tier: "10" },
    { name: "Amerigo Vespucci", speed: 29.6, type: "BB", nation: "Italy", tier: "10" },
    { name: "Cristoforo Colombo", speed: 29.6, type: "BB", nation: "Italy", tier: "10" },
    { name: "Ruggiero di Lauria", speed: 35, type: "BB", nation: "Italy", tier: "10" },
    { name: "Sicilia", speed: 29.6, type: "BB", nation: "Italy", tier: "10" },
    { name: "Tempesta Nera", speed: 35, type: "BB", nation: "Italy", tier: "10" },
    { name: "[Yamato]", speed: 27, type: "BB", nation: "Japan", tier: "10" },
    { name: "Aki", speed: 27, type: "BB", nation: "Japan", tier: "10" },
    { name: "Aki Golden", speed: 27, type: "BB", nation: "Japan", tier: "10" },
    { name: "ARP Yamato", speed: 27, type: "BB", nation: "Japan", tier: "10" },
    { name: "Bungo", speed: 30, type: "BB", nation: "Japan", tier: "10" },
    { name: "Shikishima", speed: 27, type: "BB", nation: "Japan", tier: "10" },
    { name: "Yamato", speed: 27, type: "BB", nation: "Japan", tier: "10" },
    { name: "Yamato Kai", speed: 27, type: "BB", nation: "Japan", tier: "10" },
    { name: "Willem de Eerste", speed: 32, type: "BB", nation: "Netherlands", tier: "10" },
    { name: "Comodoro", speed: 30, type: "BB", nation: "Pan-America", tier: "10" },
    { name: "Libertad", speed: 30, type: "BB", nation: "Pan-America", tier: "10" },
    { name: "[Conqueror]", speed: 29.5, type: "BB", nation: "UK", tier: "10" },
    { name: "Conqueror", speed: 29.5, type: "BB", nation: "UK", tier: "10" },
    { name: "Cumberland", speed: 31.5, type: "BB", nation: "UK", tier: "10" },
    { name: "Incomparable", speed: 33, type: "BB", nation: "UK", tier: "10" },
    { name: "St. Vincent", speed: 32.5, type: "BB", nation: "UK", tier: "10" },
    { name: "Thunderer", speed: 29.5, type: "BB", nation: "UK", tier: "10" },
    { name: "[Montana]", speed: 30, type: "BB", nation: "USA", tier: "10" },
    { name: "BA Montana", speed: 30, type: "BB", nation: "USA", tier: "10" },
    { name: "Louisiana", speed: 31, type: "BB", nation: "USA", tier: "10" },
    { name: "Montana", speed: 30, type: "BB", nation: "USA", tier: "10" },
    { name: "Montana 2", speed: 30, type: "BB", nation: "USA", tier: "10" },
    { name: "Ohio", speed: 28, type: "BB", nation: "USA", tier: "10" },
    { name: "Oregon", speed: 33, type: "BB", nation: "USA", tier: "10" },
    { name: "Rhode Island", speed: 33, type: "BB", nation: "USA", tier: "10" },
    { name: "Rhode Island B", speed: 33, type: "BB", nation: "USA", tier: "10" },
    { name: "Utah", speed: 23, type: "BB", nation: "USA", tier: "10" },
    { name: "Vermont", speed: 23, type: "BB", nation: "USA", tier: "10" },
    { name: "Wisconsin", speed: 32.5, type: "BB", nation: "USA", tier: "10" },
    { name: "Kremlin", speed: 29.5, type: "BB", nation: "USSR", tier: "10" },
    { name: "Sibir", speed: 29.5, type: "BB", nation: "USSR", tier: "10" },
    { name: "Slava", speed: 29.5, type: "BB", nation: "USSR", tier: "10" },
    { name: "Brisbane", speed: 33.5, type: "CA", nation: "Commonwealth", tier: "10" },
    { name: "Brisbane B", speed: 33.5, type: "CA", nation: "Commonwealth", tier: "10" },
    { name: "Cerberus", speed: 34, type: "CA", nation: "Commonwealth", tier: "10" },
    { name: "Pioneer", speed: 34, type: "CA", nation: "Commonwealth", tier: "10" },
    { name: "Svea", speed: 34, type: "CA", nation: "Europe", tier: "10" },
    { name: "Amiral Lartigue", speed: 34, type: "CA", nation: "France", tier: "10" },
    { name: "Brennus", speed: 35, type: "CA", nation: "France", tier: "10" },
    { name: "Colbert", speed: 33, type: "CA", nation: "France", tier: "10" },
    { name: "Henri IV", speed: 35, type: "CA", nation: "France", tier: "10" },
    { name: "Marseille", speed: 33, type: "CA", nation: "France", tier: "10" },
    { name: "[Hindenburg]", speed: 31.5, type: "CA", nation: "Germany", tier: "10" },
    { name: "AL Hindenburg", speed: 31.5, type: "CA", nation: "Germany", tier: "10" },
    { name: "Bremen", speed: 32.5, type: "CA", nation: "Germany", tier: "10" },
    { name: "Bremen Golden", speed: 32.5, type: "CA", nation: "Germany", tier: "10" },
    { name: "Hildebrand", speed: 34, type: "CA", nation: "Germany", tier: "10" },
    { name: "Hindenburg", speed: 31.5, type: "CA", nation: "Germany", tier: "10" },
    { name: "Prinz Adalbert", speed: 33, type: "CA", nation: "Germany", tier: "10" },
    { name: "Napoli", speed: 35.5, type: "CA", nation: "Italy", tier: "10" },
    { name: "Napoli B", speed: 35.5, type: "CA", nation: "Italy", tier: "10" },
    { name: "Ravenna", speed: 36.6, type: "CA", nation: "Italy", tier: "10" },
    { name: "Varese", speed: 33, type: "CA", nation: "Italy", tier: "10" },
    { name: "Venezia", speed: 36.6, type: "CA", nation: "Italy", tier: "10" },
    { name: "[Zaō]", speed: 34.5, type: "CA", nation: "Japan", tier: "10" },
    { name: "Kitakami", speed: 36, type: "CA", nation: "Japan", tier: "10" },
    { name: "Kushiro", speed: 34.5, type: "CA", nation: "Japan", tier: "10" },
    { name: "Yari", speed: 34.5, type: "CA", nation: "Japan", tier: "10" },
    { name: "Yodo", speed: 34, type: "CA", nation: "Japan", tier: "10" },
    { name: "Yoshino", speed: 34, type: "CA", nation: "Japan", tier: "10" },
    { name: "Yoshino B", speed: 34, type: "CA", nation: "Japan", tier: "10" },
    { name: "Zaō", speed: 34.5, type: "CA", nation: "Japan", tier: "10" },
    { name: "Zaō CLR", speed: 34.5, type: "CA", nation: "Japan", tier: "10" },
    { name: "Gouden Leeuw", speed: 33.5, type: "CA", nation: "Netherlands", tier: "10" },
    { name: "Noord-Brabant", speed: 35, type: "CA", nation: "Netherlands", tier: "10" },
    { name: "Prins van Oranje", speed: 33.5, type: "CA", nation: "Netherlands", tier: "10" },
    { name: "Prins van Oranje Golden", speed: 33.5, type: "CA", nation: "Netherlands", tier: "10" },
    { name: "Utrecht", speed: 35, type: "CA", nation: "Netherlands", tier: "10" },
    { name: "Vrijheid", speed: 33.5, type: "CA", nation: "Netherlands", tier: "10" },
    { name: "San Martín", speed: 34, type: "CA", nation: "Pan-America", tier: "10" },
    { name: "Incheon", speed: 33, type: "CA", nation: "Pan-Asia", tier: "10" },
    { name: "Jinan", speed: 35, type: "CA", nation: "Pan-Asia", tier: "10" },
    { name: "Zhuge's Inventions", speed: 33, type: "CA", nation: "Pan-Asia", tier: "10" },
    { name: "Castilla", speed: 37, type: "CA", nation: "Spain", tier: "10" },
    { name: "Defence", speed: 33, type: "CA", nation: "UK", tier: "10" },
    { name: "Gibraltar", speed: 32, type: "CA", nation: "UK", tier: "10" },
    { name: "Goliath", speed: 33, type: "CA", nation: "UK", tier: "10" },
    { name: "Minotaur", speed: 33.5, type: "CA", nation: "UK", tier: "10" },
    { name: "Monmouth", speed: 32, type: "CA", nation: "UK", tier: "10" },
    { name: "Plymouth", speed: 31.5, type: "CA", nation: "UK", tier: "10" },
    { name: "Austin", speed: 35, type: "CA", nation: "USA", tier: "10" },
    { name: "Des Moines", speed: 33, type: "CA", nation: "USA", tier: "10" },
    { name: "Hawaii", speed: 33, type: "CA", nation: "USA", tier: "10" },
    { name: "Hawaii Golden", speed: 33, type: "CA", nation: "USA", tier: "10" },
    { name: "Puerto Rico", speed: 33.5, type: "CA", nation: "USA", tier: "10" },
    { name: "Puerto Rico B", speed: 33.5, type: "CA", nation: "USA", tier: "10" },
    { name: "Salem", speed: 33, type: "CA", nation: "USA", tier: "10" },
    { name: "Worcester", speed: 33, type: "CA", nation: "USA", tier: "10" },
    { name: "[Moskva]", speed: 34.5, type: "CA", nation: "USSR", tier: "10" },
    { name: "Alexander Nevsky", speed: 36, type: "CA", nation: "USSR", tier: "10" },
    { name: "Komissar", speed: 35.5, type: "CA", nation: "USSR", tier: "10" },
    { name: "Moskva", speed: 34.5, type: "CA", nation: "USSR", tier: "10" },
    { name: "Petropavlovsk", speed: 32.5, type: "CA", nation: "USSR", tier: "10" },
    { name: "Petrozavodsk", speed: 32.5, type: "CA", nation: "USSR", tier: "10" },
    { name: "PTRPVLSK", speed: 32.5, type: "CA", nation: "USSR", tier: "10" },
    { name: "Sevastopol", speed: 33.5, type: "CA", nation: "USSR", tier: "10" },
    { name: "Smolensk", speed: 35, type: "CA", nation: "USSR", tier: "10" },
    { name: "Smolensk B", speed: 35, type: "CA", nation: "USSR", tier: "10" },
    { name: "Stalingrad", speed: 35, type: "CA", nation: "USSR", tier: "10" },
    { name: "Vladimir Monomakh", speed: 36, type: "CA", nation: "USSR", tier: "10" },
    { name: "Manfred von Richthofen", speed: 32, type: "CV", nation: "Germany", tier: "10" },
    { name: "Max Immelmann", speed: 32, type: "CV", nation: "Germany", tier: "10" },
    { name: "Otto Lilienthal", speed: 32, type: "CV", nation: "Germany", tier: "10" },
    { name: "Süsshofen", speed: 32, type: "CV", nation: "Germany", tier: "10" },
    { name: "Werner Voss", speed: 32, type: "CV", nation: "Germany", tier: "10" },
    { name: "[Hakuryū]", speed: 34.5, type: "CV", nation: "Japan", tier: "10" },
    { name: "Hakuryū", speed: 34.5, type: "CV", nation: "Japan", tier: "10" },
    { name: "Shinano", speed: 27, type: "CV", nation: "Japan", tier: "10" },
    { name: "Independencia", speed: 25, type: "CV", nation: "Pan-America", tier: "10" },
    { name: "[Audacious]", speed: 32, type: "CV", nation: "UK", tier: "10" },
    { name: "Audacious", speed: 32, type: "CV", nation: "UK", tier: "10" },
    { name: "Malta", speed: 33.6, type: "CV", nation: "UK", tier: "10" },
    { name: "Ocean", speed: 25, type: "CV", nation: "UK", tier: "10" },
    { name: "[Midway]", speed: 33, type: "CV", nation: "USA", tier: "10" },
    { name: "Essex", speed: 33, type: "CV", nation: "USA", tier: "10" },
    { name: "Franklin D. Roosevelt", speed: 33, type: "CV", nation: "USA", tier: "10" },
    { name: "Midway", speed: 33, type: "CV", nation: "USA", tier: "10" },
    { name: "Piñatapolis", speed: 33, type: "CV", nation: "USA", tier: "10" },
    { name: "Admiral Orlov", speed: 31, type: "CV", nation: "USSR", tier: "10" },
    { name: "Vampire II", speed: 35, type: "DD", nation: "Commonwealth", tier: "10" },
    { name: "Gdańsk", speed: 41.2, type: "DD", nation: "Europe", tier: "10" },
    { name: "Halland", speed: 35, type: "DD", nation: "Europe", tier: "10" },
    { name: "Oväsen", speed: 35, type: "DD", nation: "Europe", tier: "10" },
    { name: "Ragnar", speed: 35, type: "DD", nation: "Europe", tier: "10" },
    { name: "Småland", speed: 35, type: "DD", nation: "Europe", tier: "10" },
    { name: "Södermanland", speed: 35, type: "DD", nation: "Europe", tier: "10" },
    { name: "Cassard", speed: 34, type: "DD", nation: "France", tier: "10" },
    { name: "Châteaurenault", speed: 41, type: "DD", nation: "France", tier: "10" },
    { name: "Kléber", speed: 44, type: "DD", nation: "France", tier: "10" },
    { name: "Kléber CLR", speed: 44, type: "DD", nation: "France", tier: "10" },
    { name: "Kléber TE", speed: 44, type: "DD", nation: "France", tier: "10" },
    { name: "Marceau", speed: 44, type: "DD", nation: "France", tier: "10" },
    { name: "Elbing", speed: 36.2, type: "DD", nation: "Germany", tier: "10" },
    { name: "Georg Hoffmann", speed: 37.5, type: "DD", nation: "Germany", tier: "10" },
    { name: "Georg Hoffmann Golden", speed: 37.5, type: "DD", nation: "Germany", tier: "10" },
    { name: "Lübeck", speed: 36.2, type: "DD", nation: "Germany", tier: "10" },
    { name: "Z-42", speed: 36.5, type: "DD", nation: "Germany", tier: "10" },
    { name: "Z-52", speed: 37.5, type: "DD", nation: "Germany", tier: "10" },
    { name: "Alberico da Barbiano", speed: 39.6, type: "DD", nation: "Italy", tier: "10" },
    { name: "Attilio Regolo", speed: 41, type: "DD", nation: "Italy", tier: "10" },
    { name: "[Shimakaze]", speed: 39, type: "DD", nation: "Japan", tier: "10" },
    { name: "AL Shimakaze", speed: 39, type: "DD", nation: "Japan", tier: "10" },
    { name: "Harugumo", speed: 35.7, type: "DD", nation: "Japan", tier: "10" },
    { name: "Hayate", speed: 37, type: "DD", nation: "Japan", tier: "10" },
    { name: "Shimakaze", speed: 39, type: "DD", nation: "Japan", tier: "10" },
    { name: "Tromp", speed: 33.5, type: "DD", nation: "Netherlands", tier: "10" },
    { name: "La Pampa", speed: 34, type: "DD", nation: "Pan-America", tier: "10" },
    { name: "Lüshun", speed: 36, type: "DD", nation: "Pan-Asia", tier: "10" },
    { name: "Lüshun B", speed: 36, type: "DD", nation: "Pan-Asia", tier: "10" },
    { name: "Yueyang", speed: 36.5, type: "DD", nation: "Pan-Asia", tier: "10" },
    { name: "Álvaro de Bazán", speed: 40, type: "DD", nation: "Spain", tier: "10" },
    { name: "Daring", speed: 35, type: "DD", nation: "UK", tier: "10" },
    { name: "Druid", speed: 35, type: "DD", nation: "UK", tier: "10" },
    { name: "[Gearing]", speed: 36, type: "DD", nation: "USA", tier: "10" },
    { name: "Burrows", speed: 37, type: "DD", nation: "USA", tier: "10" },
    { name: "Forrest Sherman", speed: 33.9, type: "DD", nation: "USA", tier: "10" },
    { name: "Gearing", speed: 36, type: "DD", nation: "USA", tier: "10" },
    { name: "Hull", speed: 33.9, type: "DD", nation: "USA", tier: "10" },
    { name: "Laffey", speed: 36.5, type: "DD", nation: "USA", tier: "10" },
    { name: "Somers", speed: 38.6, type: "DD", nation: "USA", tier: "10" },
    { name: "[Grozovoi]", speed: 39.5, type: "DD", nation: "USSR", tier: "10" },
    { name: "Delny", speed: 43.5, type: "DD", nation: "USSR", tier: "10" },
    { name: "Grozovoi", speed: 39.5, type: "DD", nation: "USSR", tier: "10" },
    { name: "Khabarovsk", speed: 43, type: "DD", nation: "USSR", tier: "10" },
    { name: "Surcouf", speed: 32, type: "SUB", nation: "France", tier: "10" },
    { name: "U-2501", speed: 27, type: "SUB", nation: "Germany", tier: "10" },
    { name: "U-4501", speed: 20, type: "SUB", nation: "Germany", tier: "10" },
    { name: "BA Arona's Whale", speed: 30, type: "SUB", nation: "Japan", tier: "10" },
    { name: "I-56 '44", speed: 30, type: "SUB", nation: "Japan", tier: "10" },
    { name: "Seal", speed: 27, type: "SUB", nation: "UK", tier: "10" },
    { name: "Thrasher", speed: 26, type: "SUB", nation: "UK", tier: "10" },
    { name: "Archerfish", speed: 33, type: "SUB", nation: "USA", tier: "10" },
    { name: "Balao", speed: 30, type: "SUB", nation: "USA", tier: "10" },
    { name: "Balao 2", speed: 30, type: "SUB", nation: "USA", tier: "10" },
    { name: "Gato", speed: 34, type: "SUB", nation: "USA", tier: "10" },
    { name: "K-1", speed: 37, type: "SUB", nation: "USSR", tier: "10" },
];

const attackerDatabase = [    { name: "Gustav den Store (381 mm)", velocity: 750, type: "BB", nation: "Europe", tier: "9" },
    { name: "Karl XIV Johan (305 mm)", velocity: 865, type: "BB", nation: "Europe", tier: "9" },
    { name: "Karl XIV Johan B (305 mm)", velocity: 865, type: "BB", nation: "Europe", tier: "9" },
    { name: "Niord (380 mm)", velocity: 820, type: "BB", nation: "Europe", tier: "9" },
    { name: "Alsace (380 mm)", velocity: 830, type: "BB", nation: "France", tier: "9" },
    { name: "Jean Bart (380 mm)", velocity: 830, type: "BB", nation: "France", tier: "9" },
    { name: "Jean Bart B (380 mm)", velocity: 830, type: "BB", nation: "France", tier: "9" },
    { name: "Roussillon (406 mm)", velocity: 850, type: "BB", nation: "France", tier: "9" },
    { name: "Friedrich der Grosse (406 mm)", velocity: 810, type: "BB", nation: "Germany", tier: "9" },
    { name: "Pommern (380 mm)", velocity: 820, type: "BB", nation: "Germany", tier: "9" },
    { name: "Pommern B (380 mm)", velocity: 820, type: "BB", nation: "Germany", tier: "9" },
    { name: "Prinz Rupprecht (406 mm)", velocity: 810, type: "BB", nation: "Germany", tier: "9" },
    { name: "Prinz Sigismund (380 mm)", velocity: 820, type: "BB", nation: "Germany", tier: "9" },
    { name: "Giuseppe Verdi (406 mm)", velocity: 836, type: "BB", nation: "Italy", tier: "9" },
    { name: "Lepanto (381 mm)", velocity: 850, type: "BB", nation: "Italy", tier: "9" },
    { name: "Marco Polo (406 mm)", velocity: 836, type: "BB", nation: "Italy", tier: "9" },
    { name: "Pilus Posterior (406 mm)", velocity: 836, type: "BB", nation: "Italy", tier: "9" },
    { name: "Pilus Prior (406 mm)", velocity: 836, type: "BB", nation: "Italy", tier: "9" },
    { name: "Adatara (457 mm)", velocity: 860, type: "BB", nation: "Japan", tier: "9" },
    { name: "Daisen (410 mm)", velocity: 870, type: "BB", nation: "Japan", tier: "9" },
    { name: "Hizen (410 mm)", velocity: 834, type: "BB", nation: "Japan", tier: "9" },
    { name: "Hotaka (410 mm)", velocity: 870, type: "BB", nation: "Japan", tier: "9" },
    { name: "Iwami (410 mm)", velocity: 834, type: "BB", nation: "Japan", tier: "9" },
    { name: "Iwami B (410 mm)", velocity: 834, type: "BB", nation: "Japan", tier: "9" },
    { name: "Izumo (410 mm)", velocity: 870, type: "BB", nation: "Japan", tier: "9" },
    { name: "Musashi (460 mm)", velocity: 780, type: "BB", nation: "Japan", tier: "9" },
    { name: "Tsurugi (457 mm)", velocity: 860, type: "BB", nation: "Japan", tier: "9" },
    { name: "Los Andes (381 mm)", velocity: 804, type: "BB", nation: "Pan-America", tier: "9" },
    { name: "Valparaíso (381 mm)", velocity: 804, type: "BB", nation: "Pan-America", tier: "9" },
    { name: "Bajie (410 mm)", velocity: 870, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Louchuan (419 mm)", velocity: 747, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Sun Yat-Sen (457 mm)", velocity: 800, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Taihang (406 mm)", velocity: 830, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Wujing (380 mm)", velocity: 830, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Xuan Ming (457 mm)", velocity: 800, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Xuan Wu (406 mm)", velocity: 762, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Yimeng (356 mm)", velocity: 895, type: "BB", nation: "Pan-Asia", tier: "9" },
    { name: "Victoria (381 mm)", velocity: 850, type: "BB", nation: "Spain", tier: "9" },
    { name: "Duncan (419 mm)", velocity: 747, type: "BB", nation: "UK", tier: "9" },
    { name: "Lion (406 mm)", velocity: 747, type: "BB", nation: "UK", tier: "9" },
    { name: "Marlborough (356 mm)", velocity: 757, type: "BB", nation: "UK", tier: "9" },
    { name: "Scarlet Thunder (419 mm)", velocity: 747, type: "BB", nation: "UK", tier: "9" },
    { name: "AL Kearsarge (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "9" },
    { name: "Delaware (406 mm)", velocity: 762, type: "BB", nation: "USA", tier: "9" },
    { name: "Georgia (457 mm)", velocity: 732, type: "BB", nation: "USA", tier: "9" },
    { name: "Illinois (203 mm)", velocity: 762, type: "BB", nation: "USA", tier: "9" },
    { name: "Indiana (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "9" },
    { name: "Iowa (406 mm)", velocity: 762, type: "BB", nation: "USA", tier: "9" },
    { name: "Iowa 2 (406 mm)", velocity: 762, type: "BB", nation: "USA", tier: "9" },
    { name: "Kearsarge (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "9" },
    { name: "Kearsarge B (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "9" },
    { name: "Minnesota (406 mm)", velocity: 762, type: "BB", nation: "USA", tier: "9" },
    { name: "Missouri (406 mm)", velocity: 762, type: "BB", nation: "USA", tier: "9" },
    { name: "AL Sov. Rossiya (406 mm)", velocity: 830, type: "BB", nation: "USSR", tier: "9" },
    { name: "BA Hovercraft (406 mm)", velocity: 793, type: "BB", nation: "USSR", tier: "9" },
    { name: "Navarin (406 mm)", velocity: 793, type: "BB", nation: "USSR", tier: "9" },
    { name: "Sovetsky Soyuz (406 mm)", velocity: 830, type: "BB", nation: "USSR", tier: "9" },
    { name: "Zarya Svobody (406 mm)", velocity: 793, type: "BB", nation: "USSR", tier: "9" },
    { name: "Encounter (203 mm)", velocity: 841, type: "CA", nation: "Commonwealth", tier: "9" },
    { name: "Hector (133 mm)", velocity: 792, type: "CA", nation: "Commonwealth", tier: "9" },
    { name: "BA Utnapishtim's Ship (330 mm)", velocity: 870, type: "CA", nation: "France", tier: "9" },
    { name: "Brest (330 mm)", velocity: 870, type: "CA", nation: "France", tier: "9" },
    { name: "Carnot (305 mm)", velocity: 870, type: "CA", nation: "France", tier: "9" },
    { name: "Le Havre (330 mm)", velocity: 870, type: "CA", nation: "France", tier: "9" },
    { name: "Saint-Louis (203 mm)", velocity: 845, type: "CA", nation: "France", tier: "9" },
    { name: "Admiral Schröder (305 mm)", velocity: 855, type: "CA", nation: "Germany", tier: "9" },
    { name: "Ägir (305 mm)", velocity: 865, type: "CA", nation: "Germany", tier: "9" },
    { name: "AL Ägir (305 mm)", velocity: 865, type: "CA", nation: "Germany", tier: "9" },
    { name: "Blücher (203 mm)", velocity: 925, type: "CA", nation: "Germany", tier: "9" },
    { name: "Manteuffel (350 mm)", velocity: 815, type: "CA", nation: "Germany", tier: "9" },
    { name: "Roon (203 mm)", velocity: 925, type: "CA", nation: "Germany", tier: "9" },
    { name: "Roon CLR (203 mm)", velocity: 925, type: "CA", nation: "Germany", tier: "9" },
    { name: "Siegfried (380 mm)", velocity: 820, type: "CA", nation: "Germany", tier: "9" },
    { name: "Brindisi (203 mm)", velocity: 910, type: "CA", nation: "Italy", tier: "9" },
    { name: "Ferrante Gonzaga (135 mm)", velocity: 875, type: "CA", nation: "Italy", tier: "9" },
    { name: "Michelangelo (320 mm)", velocity: 830, type: "CA", nation: "Italy", tier: "9" },
    { name: "AL Azuma (310 mm)", velocity: 836, type: "CA", nation: "Japan", tier: "9" },
    { name: "Azuma (310 mm)", velocity: 836, type: "CA", nation: "Japan", tier: "9" },
    { name: "Azuma B (310 mm)", velocity: 836, type: "CA", nation: "Japan", tier: "9" },
    { name: "BA Takahashi (150 mm)", velocity: 930, type: "CA", nation: "Japan", tier: "9" },
    { name: "Chikuma II (203 mm)", velocity: 840, type: "CA", nation: "Japan", tier: "9" },
    { name: "Chikuma II Golden (203 mm)", velocity: 840, type: "CA", nation: "Japan", tier: "9" },
    { name: "Ibuki (203 mm)", velocity: 840, type: "CA", nation: "Japan", tier: "9" },
    { name: "Suzuya (155 mm)", velocity: 925, type: "CA", nation: "Japan", tier: "9" },
    { name: "Suzuya Golden (155 mm)", velocity: 925, type: "CA", nation: "Japan", tier: "9" },
    { name: "Suzuya VL (155 mm)", velocity: 925, type: "CA", nation: "Japan", tier: "9" },
    { name: "Takahashi (150 mm)", velocity: 930, type: "CA", nation: "Japan", tier: "9" },
    { name: "Johan de Witt (240 mm)", velocity: 900, type: "CA", nation: "Netherlands", tier: "9" },
    { name: "Menno van Coehoorn (128 mm)", velocity: 960, type: "CA", nation: "Netherlands", tier: "9" },
    { name: "Van Speijk (203 mm)", velocity: 925, type: "CA", nation: "Netherlands", tier: "9" },
    { name: "Santander (152 mm)", velocity: 812, type: "CA", nation: "Pan-America", tier: "9" },
    { name: "Dalian (130 mm)", velocity: 950, type: "CA", nation: "Pan-Asia", tier: "9" },
    { name: "Mengchong (305 mm)", velocity: 865, type: "CA", nation: "Pan-Asia", tier: "9" },
    { name: "Sejong (127 mm)", velocity: 808, type: "CA", nation: "Pan-Asia", tier: "9" },
    { name: "Tianjin (220 mm)", velocity: 995, type: "CA", nation: "Pan-Asia", tier: "9" },
    { name: "Almirante Oquendo (203 mm)", velocity: 814, type: "CA", nation: "Spain", tier: "9" },
    { name: "Andalucía (234 mm)", velocity: 841, type: "CA", nation: "Spain", tier: "9" },
    { name: "Drake (234 mm)", velocity: 841, type: "CA", nation: "UK", tier: "9" },
    { name: "Neptune (152 mm)", velocity: 768, type: "CA", nation: "UK", tier: "9" },
    { name: "Alaska (305 mm)", velocity: 762, type: "CA", nation: "USA", tier: "9" },
    { name: "Alaska B (305 mm)", velocity: 762, type: "CA", nation: "USA", tier: "9" },
    { name: "Buffalo (203 mm)", velocity: 762, type: "CA", nation: "USA", tier: "9" },
    { name: "Cambridge (305 mm)", velocity: 762, type: "CA", nation: "USA", tier: "9" },
    { name: "Seattle (152 mm)", velocity: 762, type: "CA", nation: "USA", tier: "9" },
    { name: "Tulsa (203 mm)", velocity: 762, type: "CA", nation: "USA", tier: "9" },
    { name: "Vallejo (152 mm)", velocity: 762, type: "CA", nation: "USA", tier: "9" },
    { name: "Dmitri Donskoi", velocity: 920, type: "CA", nation: "USSR", tier: "9" },
    { name: "Kozma Minin (203 mm)", velocity: 925, type: "CA", nation: "USSR", tier: "9" },
    { name: "Kronshtadt (305 mm)", velocity: 900, type: "CA", nation: "USSR", tier: "9" },
    { name: "Riga (220 mm)", velocity: 965, type: "CA", nation: "USSR", tier: "9" },
    { name: "Vyazma (406 mm)", velocity: 830, type: "CA", nation: "USSR", tier: "9" },
    { name: "Błyskawica '52 (100 mm)", velocity: 895, type: "DD", nation: "Europe", tier: "9" },
    { name: "Friesland (120 mm)", velocity: 825, type: "DD", nation: "Europe", tier: "9" },
    { name: "Jäger (150 mm)", velocity: 880, type: "DD", nation: "Europe", tier: "9" },
    { name: "Lambros Katsonis (140 mm)", velocity: 840, type: "DD", nation: "Europe", tier: "9" },
    { name: "Östergötland (120 mm)", velocity: 850, type: "DD", nation: "Europe", tier: "9" },
    { name: "Velos (127 mm)", velocity: 792, type: "DD", nation: "Europe", tier: "9" },
    { name: "Mogador (139 mm)", velocity: 840, type: "DD", nation: "France", tier: "9" },
    { name: "Orage (127 mm)", velocity: 808, type: "DD", nation: "France", tier: "9" },
    { name: "Felix Schultz (150 mm)", velocity: 960, type: "DD", nation: "Germany", tier: "9" },
    { name: "Z-44 (128 mm)", velocity: 830, type: "DD", nation: "Germany", tier: "9" },
    { name: "Z-46 (128 mm)", velocity: 830, type: "DD", nation: "Germany", tier: "9" },
    { name: "ZF-6 (128 mm)", velocity: 880, type: "DD", nation: "Germany", tier: "9" },
    { name: "ZF-6 Golden (128 mm)", velocity: 880, type: "DD", nation: "Germany", tier: "9" },
    { name: "Adriatico (135 mm)", velocity: 875, type: "DD", nation: "Italy", tier: "9" },
    { name: "Paolo Emilio (135 mm)", velocity: 875, type: "DD", nation: "Italy", tier: "9" },
    { name: "Kitakaze (100 mm)", velocity: 1000, type: "DD", nation: "Japan", tier: "9" },
    { name: "Minegumo (127 mm)", velocity: 915, type: "DD", nation: "Japan", tier: "9" },
    { name: "STAR Kitakaze (100 mm)", velocity: 1000, type: "DD", nation: "Japan", tier: "9" },
    { name: "Yūgumo (127 mm)", velocity: 915, type: "DD", nation: "Japan", tier: "9" },
    { name: "Groningen (120 mm)", velocity: 825, type: "DD", nation: "Netherlands", tier: "9" },
    { name: "Chung Mu (127 mm)", velocity: 792, type: "DD", nation: "Pan-Asia", tier: "9" },
    { name: "Nanning", velocity: 950, type: "DD", nation: "Pan-Asia", tier: "9" },
    { name: "Barfleur (113 mm)", velocity: 746, type: "DD", nation: "UK", tier: "9" },
    { name: "Jutland (113 mm)", velocity: 746, type: "DD", nation: "UK", tier: "9" },
    { name: "Somme (113 mm)", velocity: 746, type: "DD", nation: "UK", tier: "9" },
    { name: "Benham (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "9" },
    { name: "Black (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "9" },
    { name: "Black B (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "9" },
    { name: "Christopher (137 mm)", velocity: 823, type: "DD", nation: "USA", tier: "9" },
    { name: "Fletcher (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "9" },
    { name: "Frank Friday (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "9" },
    { name: "GQ Johnny (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "9" },
    { name: "Halford (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "9" },
    { name: "Johnston (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "9" },
    { name: "Neustrashimy", velocity: 950, type: "DD", nation: "USSR", tier: "9" },
    { name: "Neustrashimy B", velocity: 950, type: "DD", nation: "USSR", tier: "9" },
    { name: "Tashkent", velocity: 870, type: "DD", nation: "USSR", tier: "9" },
    { name: "Udaloi", velocity: 900, type: "DD", nation: "USSR", tier: "9" },
    { name: "Enigheten (381 mm)", velocity: 750, type: "BB", nation: "Europe", tier: "8" },
    { name: "Turgut Reis (419 mm)", velocity: 747, type: "BB", nation: "Europe", tier: "8" },
    { name: "Champagne (406 mm)", velocity: 850, type: "BB", nation: "France", tier: "8" },
    { name: "Flandre (380 mm)", velocity: 830, type: "BB", nation: "France", tier: "8" },
    { name: "Gascogne (380 mm)", velocity: 830, type: "BB", nation: "France", tier: "8" },
    { name: "Picardie (305 mm)", velocity: 798, type: "BB", nation: "France", tier: "8" },
    { name: "Richelieu (380 mm)", velocity: 830, type: "BB", nation: "France", tier: "8" },
    { name: "AL Bismarck (380 mm)", velocity: 820, type: "BB", nation: "Germany", tier: "8" },
    { name: "Anhalt (350 mm)", velocity: 815, type: "BB", nation: "Germany", tier: "8" },
    { name: "BA Tirpitz (380 mm)", velocity: 820, type: "BB", nation: "Germany", tier: "8" },
    { name: "Bismarck (380 mm)", velocity: 820, type: "BB", nation: "Germany", tier: "8" },
    { name: "Brandenburg (305 mm)", velocity: 865, type: "BB", nation: "Germany", tier: "8" },
    { name: "Brandenburg B (305 mm)", velocity: 865, type: "BB", nation: "Germany", tier: "8" },
    { name: "Odin (305 mm)", velocity: 865, type: "BB", nation: "Germany", tier: "8" },
    { name: "Odin TE (305 mm)", velocity: 865, type: "BB", nation: "Germany", tier: "8" },
    { name: "Tirpitz (380 mm)", velocity: 820, type: "BB", nation: "Germany", tier: "8" },
    { name: "Tirpitz B (380 mm)", velocity: 820, type: "BB", nation: "Germany", tier: "8" },
    { name: "Wahnsinn (406 mm)", velocity: 810, type: "BB", nation: "Germany", tier: "8" },
    { name: "Zieten (406 mm)", velocity: 810, type: "BB", nation: "Germany", tier: "8" },
    { name: "AL Littorio (381 mm)", velocity: 850, type: "BB", nation: "Italy", tier: "8" },
    { name: "BA Binah (381 mm)", velocity: 850, type: "BB", nation: "Italy", tier: "8" },
    { name: "Marcantonio Colonna (381 mm)", velocity: 850, type: "BB", nation: "Italy", tier: "8" },
    { name: "Roma (381 mm)", velocity: 850, type: "BB", nation: "Italy", tier: "8" },
    { name: "Roma Aeterna (381 mm)", velocity: 850, type: "BB", nation: "Italy", tier: "8" },
    { name: "Vittorio Veneto (381 mm)", velocity: 850, type: "BB", nation: "Italy", tier: "8" },
    { name: "Amagi (410 mm)", velocity: 806, type: "BB", nation: "Japan", tier: "8" },
    { name: "Ignis Purgatio (410 mm)", velocity: 806, type: "BB", nation: "Japan", tier: "8" },
    { name: "Kii (410 mm)", velocity: 806, type: "BB", nation: "Japan", tier: "8" },
    { name: "Ragnarok (410 mm)", velocity: 806, type: "BB", nation: "Japan", tier: "8" },
    { name: "Yumihari (410 mm)", velocity: 870, type: "BB", nation: "Japan", tier: "8" },
    { name: "Atlântico (381 mm)", velocity: 804, type: "BB", nation: "Pan-America", tier: "8" },
    { name: "Ipiranga (356 mm)", velocity: 757, type: "BB", nation: "Pan-America", tier: "8" },
    { name: "Hawke (406 mm)", velocity: 747, type: "BB", nation: "UK", tier: "8" },
    { name: "Monarch (381 mm)", velocity: 836, type: "BB", nation: "UK", tier: "8" },
    { name: "Vanguard (381 mm)", velocity: 804, type: "BB", nation: "UK", tier: "8" },
    { name: "Alabama (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "8" },
    { name: "Alabama B (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "8" },
    { name: "Alabama ST (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "8" },
    { name: "Alabama VL (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "8" },
    { name: "Constellation (406 mm)", velocity: 768, type: "BB", nation: "USA", tier: "8" },
    { name: "Kansas (406 mm)", velocity: 768, type: "BB", nation: "USA", tier: "8" },
    { name: "Massachusetts (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "8" },
    { name: "Massachusetts B (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "8" },
    { name: "Nebraska (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "8" },
    { name: "North Carolina (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "8" },
    { name: "North Carolina 2 (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "8" },
    { name: "North Carolina CLR (406 mm)", velocity: 701, type: "BB", nation: "USA", tier: "8" },
    { name: "Tennessee (356 mm)", velocity: 823, type: "BB", nation: "USA", tier: "8" },
    { name: "Volunteer State (356 mm)", velocity: 823, type: "BB", nation: "USA", tier: "8" },
    { name: "Borodino (406 mm)", velocity: 830, type: "BB", nation: "USSR", tier: "8" },
    { name: "Borodino TE (406 mm)", velocity: 830, type: "BB", nation: "USSR", tier: "8" },
    { name: "Lenin (406 mm)", velocity: 793, type: "BB", nation: "USSR", tier: "8" },
    { name: "Vladivostok (406 mm)", velocity: 793, type: "BB", nation: "USSR", tier: "8" },
    { name: "Auckland (203 mm)", velocity: 841, type: "CA", nation: "Commonwealth", tier: "8" },
    { name: "Bayard (152 mm)", velocity: 870, type: "CA", nation: "France", tier: "8" },
    { name: "Charles Martel (203 mm)", velocity: 820, type: "CA", nation: "France", tier: "8" },
    { name: "Cherbourg (305 mm)", velocity: 870, type: "CA", nation: "France", tier: "8" },
    { name: "Metz (305 mm)", velocity: 850, type: "CA", nation: "France", tier: "8" },
    { name: "Admiral Hipper (203 mm)", velocity: 925, type: "CA", nation: "Germany", tier: "8" },
    { name: "Cross of Dorn (150 mm)", velocity: 960, type: "CA", nation: "Germany", tier: "8" },
    { name: "Knesebeck (305 mm)", velocity: 865, type: "CA", nation: "Germany", tier: "8" },
    { name: "Mainz (150 mm)", velocity: 960, type: "CA", nation: "Germany", tier: "8" },
    { name: "Mainz B (150 mm)", velocity: 960, type: "CA", nation: "Germany", tier: "8" },
    { name: "Prinz Eugen (203 mm)", velocity: 925, type: "CA", nation: "Germany", tier: "8" },
    { name: "Schill (283 mm)", velocity: 910, type: "CA", nation: "Germany", tier: "8" },
    { name: "Schill B (283 mm)", velocity: 910, type: "CA", nation: "Germany", tier: "8" },
    { name: "Wiesbaden (128 mm)", velocity: 960, type: "CA", nation: "Germany", tier: "8" },
    { name: "Amalfi (203 mm)", velocity: 910, type: "CA", nation: "Italy", tier: "8" },
    { name: "ARP Maya (203 mm)", velocity: 840, type: "CA", nation: "Japan", tier: "8" },
    { name: "ARP Takao (203 mm)", velocity: 840, type: "CA", nation: "Japan", tier: "8" },
    { name: "Atago (203 mm)", velocity: 840, type: "CA", nation: "Japan", tier: "8" },
    { name: "Atago B (203 mm)", velocity: 840, type: "CA", nation: "Japan", tier: "8" },
    { name: "Mogami (155 mm)", velocity: 925, type: "CA", nation: "Japan", tier: "8" },
    { name: "Shimanto (150 mm)", velocity: 930, type: "CA", nation: "Japan", tier: "8" },
    { name: "Tone (203 mm)", velocity: 840, type: "CA", nation: "Japan", tier: "8" },
    { name: "Admiraal (128 mm)", velocity: 960, type: "CA", nation: "Netherlands", tier: "8" },
    { name: "De Zeven Provinciën (152 mm)", velocity: 900, type: "CA", nation: "Netherlands", tier: "8" },
    { name: "Haarlem (203 mm)", velocity: 925, type: "CA", nation: "Netherlands", tier: "8" },
    { name: "Jaarsveld (128 mm)", velocity: 830, type: "CA", nation: "Netherlands", tier: "8" },
    { name: "Statenland (128 mm)", velocity: 960, type: "CA", nation: "Netherlands", tier: "8" },
    { name: "Vrijheid (120 mm)", velocity: 940, type: "CA", nation: "Netherlands", tier: "8" },
    { name: "Almirante Grau (152 mm)", velocity: 900, type: "CA", nation: "Pan-America", tier: "8" },
    { name: "Comandante Aguirre (203 mm)", velocity: 925, type: "CA", nation: "Pan-America", tier: "8" },
    { name: "Ignacio Allende (152 mm)", velocity: 812, type: "CA", nation: "Pan-America", tier: "8" },
    { name: "Harbin (130 mm)", velocity: 870, type: "CA", nation: "Pan-Asia", tier: "8" },
    { name: "Irian", velocity: 950, type: "CA", nation: "Pan-Asia", tier: "8" },
    { name: "Narai (152 mm)", velocity: 768, type: "CA", nation: "Pan-Asia", tier: "8" },
    { name: "Piñatian", velocity: 950, type: "CA", nation: "Pan-Asia", tier: "8" },
    { name: "Wukong (203 mm)", velocity: 845, type: "CA", nation: "Pan-Asia", tier: "8" },
    { name: "Cataluña (203 mm)", velocity: 900, type: "CA", nation: "Spain", tier: "8" },
    { name: "Numancia (203 mm)", velocity: 814, type: "CA", nation: "Spain", tier: "8" },
    { name: "AL Cheshire (234 mm)", velocity: 841, type: "CA", nation: "UK", tier: "8" },
    { name: "Albemarle (203 mm)", velocity: 814, type: "CA", nation: "UK", tier: "8" },
    { name: "Belfast '43 (152 mm)", velocity: 841, type: "CA", nation: "UK", tier: "8" },
    { name: "Cheshire (234 mm)", velocity: 841, type: "CA", nation: "UK", tier: "8" },
    { name: "Edinburgh (152 mm)", velocity: 841, type: "CA", nation: "UK", tier: "8" },
    { name: "Érne (152 mm)", velocity: 768, type: "CA", nation: "UK", tier: "8" },
    { name: "Hampshire (203 mm)", velocity: 884, type: "CA", nation: "UK", tier: "8" },
    { name: "Nottingham (203 mm)", velocity: 814, type: "CA", nation: "UK", tier: "8" },
    { name: "Sinann (152 mm)", velocity: 841, type: "CA", nation: "UK", tier: "8" },
    { name: "STAR Edinburgh (152 mm)", velocity: 841, type: "CA", nation: "UK", tier: "8" },
    { name: "Tiger '59 (152 mm)", velocity: 768, type: "CA", nation: "UK", tier: "8" },
    { name: "AL Montpelier (152 mm)", velocity: 762, type: "CA", nation: "USA", tier: "8" },
    { name: "Anchorage (203 mm)", velocity: 853, type: "CA", nation: "USA", tier: "8" },
    { name: "Baltimore (203 mm)", velocity: 762, type: "CA", nation: "USA", tier: "8" },
    { name: "Bridgeport (203 mm)", velocity: 762, type: "CA", nation: "USA", tier: "8" },
    { name: "Cleveland (152 mm)", velocity: 762, type: "CA", nation: "USA", tier: "8" },
    { name: "Congress (305 mm)", velocity: 762, type: "CA", nation: "USA", tier: "8" },
    { name: "Protector (305 mm)", velocity: 762, type: "CA", nation: "USA", tier: "8" },
    { name: "Rochester (203 mm)", velocity: 762, type: "CA", nation: "USA", tier: "8" },
    { name: "San Diego (127 mm)", velocity: 792, type: "CA", nation: "USA", tier: "8" },
    { name: "Wichita (203 mm)", velocity: 853, type: "CA", nation: "USA", tier: "8" },
    { name: "Bagration", velocity: 930, type: "CA", nation: "USSR", tier: "8" },
    { name: "Chapayev", velocity: 950, type: "CA", nation: "USSR", tier: "8" },
    { name: "Dmitry Pozharsky", velocity: 950, type: "CA", nation: "USSR", tier: "8" },
    { name: "Kiberpankov", velocity: 950, type: "CA", nation: "USSR", tier: "8" },
    { name: "Mikhail Kutuzov", velocity: 950, type: "CA", nation: "USSR", tier: "8" },
    { name: "Ochakov", velocity: 950, type: "CA", nation: "USSR", tier: "8" },
    { name: "Pyotr Bagration", velocity: 930, type: "CA", nation: "USSR", tier: "8" },
    { name: "Tallinn", velocity: 920, type: "CA", nation: "USSR", tier: "8" },
    { name: "Błyskawica '44 (102 mm)", velocity: 811, type: "DD", nation: "Europe", tier: "8" },
    { name: "Orkan (120 mm)", velocity: 774, type: "DD", nation: "Europe", tier: "8" },
    { name: "Öland (120 mm)", velocity: 850, type: "DD", nation: "Europe", tier: "8" },
    { name: "Split (140 mm)", velocity: 840, type: "DD", nation: "Europe", tier: "8" },
    { name: "Hoche (150 mm)", velocity: 835, type: "DD", nation: "France", tier: "8" },
    { name: "L'Aventurier (130 mm)", velocity: 800, type: "DD", nation: "France", tier: "8" },
    { name: "Le Fantasque (139 mm)", velocity: 840, type: "DD", nation: "France", tier: "8" },
    { name: "Le Terrible (139 mm)", velocity: 840, type: "DD", nation: "France", tier: "8" },
    { name: "Gustav-Julius Maerker (150 mm)", velocity: 835, type: "DD", nation: "Germany", tier: "8" },
    { name: "Z-23 (128 mm)", velocity: 830, type: "DD", nation: "Germany", tier: "8" },
    { name: "Z-35 (128 mm)", velocity: 830, type: "DD", nation: "Germany", tier: "8" },
    { name: "Vittorio Cuniberti (120 mm)", velocity: 950, type: "DD", nation: "Italy", tier: "8" },
    { name: "Akizuki (100 mm)", velocity: 1000, type: "DD", nation: "Japan", tier: "8" },
    { name: "AL Yukikaze (127 mm)", velocity: 915, type: "DD", nation: "Japan", tier: "8" },
    { name: "Asashio (127 mm)", velocity: 915, type: "DD", nation: "Japan", tier: "8" },
    { name: "Asashio B (127 mm)", velocity: 915, type: "DD", nation: "Japan", tier: "8" },
    { name: "HSF Harekaze (127 mm)", velocity: 915, type: "DD", nation: "Japan", tier: "8" },
    { name: "HSF Harekaze II (150 mm)", velocity: 875, type: "DD", nation: "Japan", tier: "8" },
    { name: "Kagerō (127 mm)", velocity: 915, type: "DD", nation: "Japan", tier: "8" },
    { name: "Fenyang (100 mm)", velocity: 1000, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Hsienyang (127 mm)", velocity: 792, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Loyang (127 mm)", velocity: 792, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Loyang B (127 mm)", velocity: 792, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Ship Smasha (100 mm)", velocity: 1000, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Siliwangi (130 mm)", velocity: 870, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Zhu Que (127 mm)", velocity: 792, type: "DD", nation: "Pan-Asia", tier: "8" },
    { name: "Cossack (120 mm)", velocity: 808, type: "DD", nation: "UK", tier: "8" },
    { name: "Cossack B (120 mm)", velocity: 808, type: "DD", nation: "UK", tier: "8" },
    { name: "Eskimo (120 mm)", velocity: 808, type: "DD", nation: "UK", tier: "8" },
    { name: "Lightning (120 mm)", velocity: 774, type: "DD", nation: "UK", tier: "8" },
    { name: "Benson (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "8" },
    { name: "Kidd (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "8" },
    { name: "Osborne (137 mm)", velocity: 823, type: "DD", nation: "USA", tier: "8" },
    { name: "Kiev", velocity: 870, type: "DD", nation: "USSR", tier: "8" },
    { name: "Ognevoi", velocity: 870, type: "DD", nation: "USSR", tier: "8" },
    { name: "Provorny (150 mm)", velocity: 835, type: "DD", nation: "USSR", tier: "8" },
    { name: "Patrie (431 mm)", velocity: 840, type: "BB", nation: "France", tier: "11" },
    { name: "Hannover (483 mm)", velocity: 810, type: "BB", nation: "Germany", tier: "11" },
    { name: "Affondatore (406 mm)", velocity: 836, type: "BB", nation: "Italy", tier: "11" },
    { name: "Satsuma (510 mm)", velocity: 765, type: "BB", nation: "Japan", tier: "11" },
    { name: "Devastation (419 mm)", velocity: 747, type: "BB", nation: "UK", tier: "11" },
    { name: "Maine (406 mm)", velocity: 762, type: "BB", nation: "USA", tier: "11" },
    { name: "Admiral Ushakov (457 mm)", velocity: 800, type: "BB", nation: "USSR", tier: "11" },
    { name: "Condé (240 mm)", velocity: 845, type: "CA", nation: "France", tier: "11" },
    { name: "Clausewitz (210 mm)", velocity: 925, type: "CA", nation: "Germany", tier: "11" },
    { name: "Piemonte (254 mm)", velocity: 1000, type: "CA", nation: "Italy", tier: "11" },
    { name: "Edgar (152 mm)", velocity: 768, type: "CA", nation: "UK", tier: "11" },
    { name: "Annapolis (203 mm)", velocity: 762, type: "CA", nation: "USA", tier: "11" },
    { name: "Jacksonville (152 mm)", velocity: 762, type: "CA", nation: "USA", tier: "11" },
    { name: "Novosibirsk (254 mm)", velocity: 900, type: "CA", nation: "USSR", tier: "11" },
    { name: "Dalarna (120 mm)", velocity: 825, type: "DD", nation: "Europe", tier: "11" },
    { name: "Z-57 (128 mm)", velocity: 830, type: "DD", nation: "Germany", tier: "11" },
    { name: "Yamagiri (127 mm)", velocity: 915, type: "DD", nation: "Japan", tier: "11" },
    { name: "Kunming (127 mm)", velocity: 792, type: "DD", nation: "Pan-Asia", tier: "11" },
    { name: "Joshua Humphreys (127 mm)", velocity: 808, type: "DD", nation: "USA", tier: "11" },
    { name: "Zorkiy", velocity: 950, type: "DD", nation: "USSR", tier: "11" },
    { name: "Irresistible (234 mm)", velocity: 841, type: "BB", nation: "Commonwealth", tier: "10" },
    { name: "Thor (406 mm)", velocity: 900, type: "BB", nation: "Europe", tier: "10" },
    { name: "Bourgogne (380 mm)", velocity: 830, type: "BB", nation: "France", tier: "10" },
    { name: "République (431 mm)", velocity: 840, type: "BB", nation: "France", tier: "10" },
    { name: "[Grosser Kurfürst] (406 mm)", velocity: 810, type: "BB", nation: "Germany", tier: "10" },
    { name: "Grosser Kurfürst (406 mm)", velocity: 810, type: "BB", nation: "Germany", tier: "10" },
    { name: "Mecklenburg (305 mm)", velocity: 865, type: "BB", nation: "Germany", tier: "10" },
    { name: "Preussen (457 mm)", velocity: 810, type: "BB", nation: "Germany", tier: "10" },
    { name: "Schlieffen (420 mm)", velocity: 835, type: "BB", nation: "Germany", tier: "10" },
    { name: "Schlieffen (420 mm)", velocity: 835, type: "BB", nation: "Germany", tier: "10" },
    { name: "Von Zuckerhoff (420 mm)", velocity: 835, type: "BB", nation: "Germany", tier: "10" },
    { name: "Amerigo Vespucci (381 mm)", velocity: 850, type: "BB", nation: "Italy", tier: "10" },
    { name: "Cristoforo Colombo (381 mm)", velocity: 850, type: "BB", nation: "Italy", tier: "10" },
    { name: "Ruggiero di Lauria (457 mm)", velocity: 762, type: "BB", nation: "Italy", tier: "10" },
    { name: "Sicilia (381 mm)", velocity: 850, type: "BB", nation: "Italy", tier: "10" },
    { name: "Tempesta Nera (457 mm)", velocity: 762, type: "BB", nation: "Italy", tier: "10" },
    { name: "[Yamato] (460 mm)", velocity: 780, type: "BB", nation: "Japan", tier: "10" },
    { name: "Aki (460 mm)", velocity: 780, type: "BB", nation: "Japan", tier: "10" },
    { name: "Aki Golden (460 mm)", velocity: 780, type: "BB", nation: "Japan", tier: "10" },
    { name: "ARP Yamato (460 mm)", velocity: 780, type: "BB", nation: "Japan", tier: "10" },
    { name: "Bungo (457 mm)", velocity: 860, type: "BB", nation: "Japan", tier: "10" },
    { name: "Shikishima (510 mm)", velocity: 765, type: "BB", nation: "Japan", tier: "10" },
    { name: "Yamato (460 mm)", velocity: 780, type: "BB", nation: "Japan", tier: "10" },
    { name: "Yamato Kai (460 mm)", velocity: 780, type: "BB", nation: "Japan", tier: "10" },
    { name: "Willem de Eerste (419 mm)", velocity: 747, type: "BB", nation: "Netherlands", tier: "10" },
    { name: "Comodoro (419 mm)", velocity: 747, type: "BB", nation: "Pan-America", tier: "10" },
    { name: "Libertad (419 mm)", velocity: 747, type: "BB", nation: "Pan-America", tier: "10" },
    { name: "[Conqueror] (419 mm)", velocity: 747, type: "BB", nation: "UK", tier: "10" },
    { name: "Conqueror (419 mm)", velocity: 747, type: "BB", nation: "UK", tier: "10" },
    { name: "Cumberland (406 mm)", velocity: 830, type: "BB", nation: "UK", tier: "10" },
    { name: "Incomparable (508 mm)", velocity: 751, type: "BB", nation: "UK", tier: "10" },
    { name: "St. Vincent (457 mm)", velocity: 762, type: "BB", nation: "UK", tier: "10" },
    { name: "Thunderer (457 mm)", velocity: 762, type: "BB", nation: "UK", tier: "10" },
    { name: "[Montana] (406 mm)", velocity: 762, type: "BB", nation: "USA", tier: "10" },
    { name: "BA Montana (406 mm)", velocity: 762, type: "BB", nation: "USA", tier: "10" },
    { name: "Louisiana (406 mm)", velocity: 762, type: "BB", nation: "USA", tier: "10" },
    { name: "Montana (406 mm)", velocity: 762, type: "BB", nation: "USA", tier: "10" },
    { name: "Montana 2 (406 mm)", velocity: 762, type: "BB", nation: "USA", tier: "10" },
    { name: "Ohio (457 mm)", velocity: 732, type: "BB", nation: "USA", tier: "10" },
    { name: "Oregon (457 mm)", velocity: 732, type: "BB", nation: "USA", tier: "10" },
    { name: "Rhode Island (356 mm)", velocity: 823, type: "BB", nation: "USA", tier: "10" },
    { name: "Rhode Island B (356 mm)", velocity: 823, type: "BB", nation: "USA", tier: "10" },
    { name: "Utah (457 mm)", velocity: 732, type: "BB", nation: "USA", tier: "10" },
    { name: "Vermont (457 mm)", velocity: 732, type: "BB", nation: "USA", tier: "10" },
    { name: "Wisconsin (406 mm)", velocity: 762, type: "BB", nation: "USA", tier: "10" },
    { name: "Kremlin (457 mm)", velocity: 800, type: "BB", nation: "USSR", tier: "10" },
    { name: "Sibir (457 mm)", velocity: 800, type: "BB", nation: "USSR", tier: "10" },
    { name: "Slava (406 mm)", velocity: 870, type: "BB", nation: "USSR", tier: "10" },
    { name: "Brisbane (152 mm)", velocity: 768, type: "CA", nation: "Commonwealth", tier: "10" },
    { name: "Brisbane B (152 mm)", velocity: 768, type: "CA", nation: "Commonwealth", tier: "10" },
    { name: "Cerberus (203 mm)", velocity: 841, type: "CA", nation: "Commonwealth", tier: "10" },
    { name: "Pioneer (152 mm)", velocity: 841, type: "CA", nation: "Commonwealth", tier: "10" },
    { name: "Svea (152 mm)", velocity: 900, type: "CA", nation: "Europe", tier: "10" },
    { name: "Amiral Lartigue (330 mm)", velocity: 870, type: "CA", nation: "France", tier: "10" },
    { name: "Brennus (305 mm)", velocity: 870, type: "CA", nation: "France", tier: "10" },
    { name: "Colbert (127 mm)", velocity: 808, type: "CA", nation: "France", tier: "10" },
    { name: "Henri IV (240 mm)", velocity: 845, type: "CA", nation: "France", tier: "10" },
    { name: "Marseille (330 mm)", velocity: 870, type: "CA", nation: "France", tier: "10" },
    { name: "[Hindenburg] (203 mm)", velocity: 925, type: "CA", nation: "Germany", tier: "10" },
    { name: "AL Hindenburg (203 mm)", velocity: 925, type: "CA", nation: "Germany", tier: "10" },
    { name: "Bremen (150 mm)", velocity: 960, type: "CA", nation: "Germany", tier: "10" },
    { name: "Bremen Golden (150 mm)", velocity: 960, type: "CA", nation: "Germany", tier: "10" },
    { name: "Hildebrand (305 mm)", velocity: 865, type: "CA", nation: "Germany", tier: "10" },
    { name: "Hindenburg (203 mm)", velocity: 925, type: "CA", nation: "Germany", tier: "10" },
    { name: "Prinz Adalbert (350 mm)", velocity: 815, type: "CA", nation: "Germany", tier: "10" },
    { name: "Napoli (254 mm)", velocity: 945, type: "CA", nation: "Italy", tier: "10" },
    { name: "Napoli B (254 mm)", velocity: 945, type: "CA", nation: "Italy", tier: "10" },
    { name: "Ravenna (203 mm)", velocity: 910, type: "CA", nation: "Italy", tier: "10" },
    { name: "Varese (320 mm)", velocity: 830, type: "CA", nation: "Italy", tier: "10" },
    { name: "Venezia (203 mm)", velocity: 910, type: "CA", nation: "Italy", tier: "10" },
    { name: "[Zaō] (203 mm)", velocity: 920, type: "CA", nation: "Japan", tier: "10" },
    { name: "Kitakami (140 mm)", velocity: 850, type: "CA", nation: "Japan", tier: "10" },
    { name: "Kushiro (203 mm)", velocity: 840, type: "CA", nation: "Japan", tier: "10" },
    { name: "Yari (203 mm)", velocity: 920, type: "CA", nation: "Japan", tier: "10" },
    { name: "Yodo (150 mm)", velocity: 930, type: "CA", nation: "Japan", tier: "10" },
    { name: "Yoshino (310 mm)", velocity: 836, type: "CA", nation: "Japan", tier: "10" },
    { name: "Yoshino B (310 mm)", velocity: 836, type: "CA", nation: "Japan", tier: "10" },
    { name: "Zaō (203 mm)", velocity: 920, type: "CA", nation: "Japan", tier: "10" },
    { name: "Zaō CLR (203 mm)", velocity: 920, type: "CA", nation: "Japan", tier: "10" },
    { name: "Gouden Leeuw (283 mm)", velocity: 890, type: "CA", nation: "Netherlands", tier: "10" },
    { name: "Noord-Brabant (128 mm)", velocity: 940, type: "CA", nation: "Netherlands", tier: "10" },
    { name: "Prins van Oranje (234 mm)", velocity: 841, type: "CA", nation: "Netherlands", tier: "10" },
    { name: "Prins van Oranje Golden (234 mm)", velocity: 841, type: "CA", nation: "Netherlands", tier: "10" },
    { name: "Utrecht (128 mm)", velocity: 960, type: "CA", nation: "Netherlands", tier: "10" },
    { name: "Vrijheid (283 mm)", velocity: 890, type: "CA", nation: "Netherlands", tier: "10" },
    { name: "San Martín (152 mm)", velocity: 812, type: "CA", nation: "Pan-America", tier: "10" },
    { name: "Incheon (203 mm)", velocity: 762, type: "CA", nation: "Pan-Asia", tier: "10" },
    { name: "Jinan (127 mm)", velocity: 808, type: "CA", nation: "Pan-Asia", tier: "10" },
    { name: "Zhuge's Inventions (330 mm)", velocity: 870, type: "CA", nation: "Pan-Asia", tier: "10" },
    { name: "Castilla (254 mm)", velocity: 945, type: "CA", nation: "Spain", tier: "10" },
    { name: "Defence (356 mm)", velocity: 757, type: "CA", nation: "UK", tier: "10" },
    { name: "Gibraltar (234 mm)", velocity: 841, type: "CA", nation: "UK", tier: "10" },
    { name: "Goliath (234 mm)", velocity: 841, type: "CA", nation: "UK", tier: "10" },
    { name: "Minotaur (152 mm)", velocity: 768, type: "CA", nation: "UK", tier: "10" },
    { name: "Monmouth (234 mm)", velocity: 841, type: "CA", nation: "UK", tier: "10" },
    { name: "Plymouth (152 mm)", velocity: 841, type: "CA", nation: "UK", tier: "10" },
    { name: "Austin (127 mm)", velocity: 808, type: "CA", nation: "USA", tier: "10" },
    { name: "Des Moines (203 mm)", velocity: 762, type: "CA", nation: "USA", tier: "10" },
    { name: "Hawaii (127 mm)", velocity: 808, type: "CA", nation: "USA", tier: "10" },
    { name: "Hawaii Golden (127 mm)", velocity: 808, type: "CA", nation: "USA", tier: "10" },
    { name: "Puerto Rico (305 mm)", velocity: 762, type: "CA", nation: "USA", tier: "10" },
    { name: "Puerto Rico B (305 mm)", velocity: 762, type: "CA", nation: "USA", tier: "10" },
    { name: "Salem (203 mm)", velocity: 762, type: "CA", nation: "USA", tier: "10" },
    { name: "Worcester (152 mm)", velocity: 762, type: "CA", nation: "USA", tier: "10" },
    { name: "[Moskva]", velocity: 985, type: "CA", nation: "USSR", tier: "10" },
    { name: "Alexander Nevsky", velocity: 1000, type: "CA", nation: "USSR", tier: "10" },
    { name: "Komissar (240 mm)", velocity: 940, type: "CA", nation: "USSR", tier: "10" },
    { name: "Moskva", velocity: 985, type: "CA", nation: "USSR", tier: "10" },
    { name: "Petropavlovsk (220 mm)", velocity: 995, type: "CA", nation: "USSR", tier: "10" },
    { name: "Petrozavodsk (220 mm)", velocity: 995, type: "CA", nation: "USSR", tier: "10" },
    { name: "PTRPVLSK (220 mm)", velocity: 995, type: "CA", nation: "USSR", tier: "10" },
    { name: "Sevastopol (380 mm)", velocity: 820, type: "CA", nation: "USSR", tier: "10" },
    { name: "Smolensk", velocity: 950, type: "CA", nation: "USSR", tier: "10" },
    { name: "Smolensk B", velocity: 950, type: "CA", nation: "USSR", tier: "10" },
    { name: "Stalingrad (305 mm)", velocity: 950, type: "CA", nation: "USSR", tier: "10" },
    { name: "Vladimir Monomakh", velocity: 1000, type: "CA", nation: "USSR", tier: "10" },
    { name: "Vampire II (113 mm)", velocity: 746, type: "DD", nation: "Commonwealth", tier: "10" },
    { name: "Gdańsk (139 mm)", velocity: 840, type: "DD", nation: "Europe", tier: "10" },
    { name: "Halland (120 mm)", velocity: 825, type: "DD", nation: "Europe", tier: "10" },
    { name: "Oväsen (120 mm)", velocity: 825, type: "DD", nation: "Europe", tier: "10" },
    { name: "Ragnar (152 mm)", velocity: 900, type: "DD", nation: "Europe", tier: "10" },
    { name: "Småland (120 mm)", velocity: 825, type: "DD", nation: "Europe", tier: "10" },
    { name: "Södermanland (120 mm)", velocity: 825, type: "DD", nation: "Europe", tier: "10" },
    { name: "Cassard (127 mm)", velocity: 808, type: "DD", nation: "France", tier: "10" },
    { name: "Châteaurenault (105 mm)", velocity: 900, type: "DD", nation: "France", tier: "10" },
    { name: "Kléber (139 mm)", velocity: 840, type: "DD", nation: "France", tier: "10" },
    { name: "Kléber CLR (139 mm)", velocity: 840, type: "DD", nation: "France", tier: "10" },
    { name: "Kléber TE (139 mm)", velocity: 840, type: "DD", nation: "France", tier: "10" },
    { name: "Marceau (127 mm)", velocity: 808, type: "DD", nation: "France", tier: "10" },
    { name: "Elbing (150 mm)", velocity: 960, type: "DD", nation: "Germany", tier: "10" },
    { name: "Georg Hoffmann (150 mm)", velocity: 960, type: "DD", nation: "Germany", tier: "10" },
    { name: "Georg Hoffmann Golden (150 mm)", velocity: 960, type: "DD", nation: "Germany", tier: "10" },
    { name: "Lübeck (150 mm)", velocity: 960, type: "DD", nation: "Germany", tier: "10" },
    { name: "Z-42 (105 mm)", velocity: 900, type: "DD", nation: "Germany", tier: "10" },
    { name: "Z-52 (128 mm)", velocity: 830, type: "DD", nation: "Germany", tier: "10" },
    { name: "Attilio Regolo (135 mm)", velocity: 875, type: "DD", nation: "Italy", tier: "10" },
    { name: "[Shimakaze] (127 mm)", velocity: 915, type: "DD", nation: "Japan", tier: "10" },
    { name: "AL Shimakaze (127 mm)", velocity: 915, type: "DD", nation: "Japan", tier: "10" },
    { name: "Harugumo (100 mm)", velocity: 1000, type: "DD", nation: "Japan", tier: "10" },
    { name: "Hayate (127 mm)", velocity: 915, type: "DD", nation: "Japan", tier: "10" },
    { name: "Shimakaze (127 mm)", velocity: 915, type: "DD", nation: "Japan", tier: "10" },
    { name: "Tromp (150 mm)", velocity: 900, type: "DD", nation: "Netherlands", tier: "10" },
    { name: "La Pampa (113 mm)", velocity: 746, type: "DD", nation: "Pan-America", tier: "10" },
    { name: "Lüshun", velocity: 950, type: "DD", nation: "Pan-Asia", tier: "10" },
    { name: "Lüshun B", velocity: 950, type: "DD", nation: "Pan-Asia", tier: "10" },
    { name: "Yueyang (127 mm)", velocity: 792, type: "DD", nation: "Pan-Asia", tier: "10" },
    { name: "Álvaro de Bazán (135 mm)", velocity: 825, type: "DD", nation: "Spain", tier: "10" },
    { name: "Daring (113 mm)", velocity: 746, type: "DD", nation: "UK", tier: "10" },
    { name: "Druid (127 mm)", velocity: 975, type: "DD", nation: "UK", tier: "10" },
    { name: "[Gearing] (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "10" },
    { name: "Burrows (137 mm)", velocity: 823, type: "DD", nation: "USA", tier: "10" },
    { name: "Forrest Sherman (127 mm)", velocity: 808, type: "DD", nation: "USA", tier: "10" },
    { name: "Gearing (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "10" },
    { name: "Hull (203 mm)", velocity: 899, type: "DD", nation: "USA", tier: "10" },
    { name: "Laffey (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "10" },
    { name: "Somers (127 mm)", velocity: 792, type: "DD", nation: "USA", tier: "10" },
    { name: "[Grozovoi]", velocity: 950, type: "DD", nation: "USSR", tier: "10" },
    { name: "Delny", velocity: 950, type: "DD", nation: "USSR", tier: "10" },
    { name: "Grozovoi", velocity: 950, type: "DD", nation: "USSR", tier: "10" },
    { name: "Khabarovsk", velocity: 900, type: "DD", nation: "USSR", tier: "10" },
    { name: "Surcouf (203 mm)", velocity: 895, type: "SUB", nation: "France", tier: "10" },
    { name: "BA Arona's Whale (140 mm)", velocity: 850, type: "SUB", nation: "Japan", tier: "10" },
    { name: "I-56 '44 (140 mm)", velocity: 850, type: "SUB", nation: "Japan", tier: "10" },
];

